# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-16 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplePingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_start_time_seconds', models.IntegerField(blank=True, null=True)),
                ('summary_type', models.CharField(choices=[('activities', 'Activities'), ('sleeps', 'Sleeps'), ('heart_rate', 'Heart rate'), ('steps', 'Steps')], max_length=100)),
                ('state', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='unprocessed', max_length=100)),
                ('notification', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppleDataSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_steps_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='applepingnotification',
            index=models.Index(fields=['user', 'upload_start_time_seconds'], name='apple_apple_user_id_fca057_idx'),
        ),
        migrations.AddIndex(
            model_name='applepingnotification',
            index=models.Index(fields=['-created_at'], name='apple_apple_created_8c474d_idx'),
        ),
        migrations.AddIndex(
            model_name='applepingnotification',
            index=models.Index(fields=['upload_start_time_seconds'], name='apple_apple_upload__7e6e16_idx'),
        ),
    ]
