# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-14 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppleDataActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_activities_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
