# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
