# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-08 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0005_auto_20190408_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appleuser',
            name='created_at',
        ),
    ]
