def all_age_aa_ranges():
	aa_dashboard = {'13':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-140':{'color':'lightgreen','classification':'Aerobic'},
	                     '141-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-165':{'color':'lightgreen','classification':'Aerobic'},
	                     '166-169':{'color':'yellow','classification':'Aerobic'},
	                     '170-174':{'color':'orange','classification':'Anerobic'},
	                     '175-178':{'color':'lightgreen','classification':'Anerobic'},
	                     '179-181':{'color':'thickgreen','classification':'Anerobic'},
	                     '182-186':{'color':'lightgreen','classification':'Anerobic'},
                         '187-189':{'color':'yellow','classification':'Anerobic'},
                         '190-191':{'color':'orange','classification':'Anerobic'},
                         '192-240':{'color':'red','classification':'Anerobic'}},

                            
	                '14':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-140':{'color':'lightgreen','classification':'Aerobic'},
	                     '141-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-165':{'color':'lightgreen','classification':'Aerobic'},
	                     '166-169':{'color':'yellow','classification':'Aerobic'},
	                     '170-174':{'color':'orange','classification':'Anerobic'},
	                     '175-178':{'color':'lightgreen','classification':'Anerobic'},
	                     '179-181':{'color':'thickgreen','classification':'Anerobic'},
	                     '182-186':{'color':'lightgreen','classification':'Anerobic'},
                         '187-189':{'color':'yellow','classification':'Anerobic'},
                         '190-191':{'color':'orange','classification':'Anerobic'},
                         '192-240':{'color':'red','classification':'Anerobic'}},
     

                    '15':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-138':{'color':'lightgreen','classification':'Aerobic'},
	                     '139-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-165':{'color':'lightgreen','classification':'Aerobic'},
	                     '166-169':{'color':'yellow','classification':'Aerobic'},
	                     '170-174':{'color':'orange','classification':'Anerobic'},
	                     '175-178':{'color':'lightgreen','classification':'Anerobic'},
	                     '179-181':{'color':'thickgreen','classification':'Anerobic'},
	                     '182-186':{'color':'lightgreen','classification':'Anerobic'},
                         '187-189':{'color':'yellow','classification':'Anerobic'},
                         '190-191':{'color':'orange','classification':'Anerobic'},
                         '192-240':{'color':'red','classification':'Anerobic'}},
	
           
                 
                    '16':{'0-109':{'color':'red','classification':'Below_Aerobic'},
                         '110-120':{'color':'yellow','classification':'Aerobic'},
                         '121-137':{'color':'lightgreen','classification':'Aerobic'},
                         '138-152':{'color':'thickgreen','classification':'Aerobic'},
                         '153-164':{'color':'lightgreen','classification':'Aerobic'},
                         '165-168':{'color':'yellow','classification':'Aerobic'},
                         '169-173':{'color':'orange','classification':'Anerobic'},
                         '174-177':{'color':'lightgreen','classification':'Anerobic'},
                         '178-180':{'color':'thickgreen','classification':'Anerobic'},
                         '181-185':{'color':'lightgreen','classification':'Anerobic'},
                         '186-188':{'color':'yellow','classification':'Anerobic'},
                         '189-190':{'color':'orange','classification':'Anerobic'},
                         '191-240':{'color':'red','classification':'Anerobic'}},




                    '17':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-136':{'color':'lightgreen','classification':'Aerobic'},
	                     '137-152':{'color':'thickgreen','classification':'Aerobic'},
	                    '153-163':{'color':'lightgreen','classification':'Aerobic'},
	                     '164-167':{'color':'yellow','classification':'Aerobic'},
	                     '168-172':{'color':'orange','classification':'Anerobic'},
	                     '173-176':{'color':'lightgreen','classification':'Anerobic'},
	                     '177-179':{'color':'thickgreen','classification':'Anerobic'},
	                     '180-184':{'color':'lightgreen','classification':'Anerobic'},
                         '185-187':{'color':'yellow','classification':'Anerobic'},
                         '188-189':{'color':'orange','classification':'Anerobic'},
                         '190-240':{'color':'red','classification':'Anerobic'}},     


                    '18':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-135':{'color':'lightgreen','classification':'Aerobic'},
	                     '136-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-162':{'color':'lightgreen','classification':'Aerobic'},
	                     '163-166':{'color':'yellow','classification':'Aerobic'},
	                     '167-171':{'color':'orange','classification':'Anerobic'},
	                     '172-175':{'color':'lightgreen','classification':'Anerobic'},
	                     '176-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},   
  



                    '19':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-134':{'color':'lightgreen','classification':'Aerobic'},
	                     '135-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-161':{'color':'lightgreen','classification':'Aerobic'},
	                     '162-165':{'color':'yellow','classification':'Aerobic'},
	                     '166-170':{'color':'orange','classification':'Anerobic'},
	                     '171-173':{'color':'lightgreen','classification':'Anerobic'},
	                     '174-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},   



                    '20':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-133':{'color':'lightgreen','classification':'Aerobic'},
	                     '134-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-160':{'color':'lightgreen','classification':'Aerobic'},
	                     '161-164':{'color':'yellow','classification':'Aerobic'},
	                     '165-169':{'color':'orange','classification':'Anerobic'},
	                     '170-172':{'color':'lightgreen','classification':'Anerobic'},
	                     '173-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        

                    '21':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-132':{'color':'lightgreen','classification':'Aerobic'},
	                     '133-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-159':{'color':'lightgreen','classification':'Aerobic'},
	                     '160-163':{'color':'yellow','classification':'Aerobic'},
	                     '164-168':{'color':'orange','classification':'Anerobic'},
	                     '169-171':{'color':'lightgreen','classification':'Anerobic'},
	                     '172-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        

            
                    '22':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-131':{'color':'lightgreen','classification':'Aerobic'},
	                     '132-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-158':{'color':'lightgreen','classification':'Aerobic'},
	                     '159-162':{'color':'yellow','classification':'Aerobic'},
	                     '163-167':{'color':'orange','classification':'Anerobic'},
	                     '168-170':{'color':'lightgreen','classification':'Anerobic'},
	                     '171-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        

            
                    '23':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-130':{'color':'lightgreen','classification':'Aerobic'},
	                     '131-152':{'color':'thickgreen','classification':'Aerobic'},
	                     '153-157':{'color':'lightgreen','classification':'Aerobic'},
	                     '158-161':{'color':'yellow','classification':'Aerobic'},
	                     '162-166':{'color':'orange','classification':'Anerobic'},
	                     '167-169':{'color':'lightgreen','classification':'Anerobic'},
	                     '170-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        
            
                    '24':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-129':{'color':'lightgreen','classification':'Aerobic'},
	                     '130-151':{'color':'thickgreen','classification':'Aerobic'},
	                     '152-156':{'color':'lightgreen','classification':'Aerobic'},
	                     '157-160':{'color':'yellow','classification':'Aerobic'},
	                     '161-165':{'color':'orange','classification':'Anerobic'},
	                     '166-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},            



                    '25':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-119':{'color':'yellow','classification':'Aerobic'},
	                     '120-128':{'color':'lightgreen','classification':'Aerobic'},
	                     '129-150':{'color':'thickgreen','classification':'Aerobic'},
	                    '151-155':{'color':'lightgreen','classification':'Aerobic'},
	                     '156-159':{'color':'yellow','classification':'Aerobic'},
	                    '160-164':{'color':'orange','classification':'Anerobic'},
	                     '165-167':{'color':'lightgreen','classification':'Anerobic'},
	                     '168-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                        '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        
            
            
                   

                    '26':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-118':{'color':'yellow','classification':'Aerobic'},
	                     '119-127':{'color':'lightgreen','classification':'Aerobic'},
	                     '128-149':{'color':'thickgreen','classification':'Aerobic'},
	                    '150-154':{'color':'lightgreen','classification':'Aerobic'},
	                    '155-158':{'color':'yellow','classification':'Aerobic'},
	                     '159-163':{'color':'orange','classification':'Anerobic'},
	                    '164-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
           

                     '27':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-117':{'color':'yellow','classification':'Aerobic'},
	                     '118-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-148':{'color':'thickgreen','classification':'Aerobic'},
	                     '149-154':{'color':'lightgreen','classification':'Aerobic'},
	                    '155-158':{'color':'yellow','classification':'Aerobic'},
	                    '159-163':{'color':'orange','classification':'Anerobic'},
	                     '164-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
             

                    '28':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-116':{'color':'yellow','classification':'Aerobic'},
	                     '117-125':{'color':'lightgreen','classification':'Aerobic'},
	                     '126-147':{'color':'thickgreen','classification':'Aerobic'},
	                     '148-154':{'color':'lightgreen','classification':'Aerobic'},
	                     '155-158':{'color':'yellow','classification':'Aerobic'},
	                     '159-163':{'color':'orange','classification':'Anerobic'},
	                     '164-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
           

                    '29':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                    '110-115':{'color':'yellow','classification':'Aerobic'},
	                     '116-124':{'color':'lightgreen','classification':'Aerobic'},
	                     '125-146':{'color':'thickgreen','classification':'Aerobic'},
	                     '147-154':{'color':'lightgreen','classification':'Aerobic'},
	                     '155-158':{'color':'yellow','classification':'Aerobic'},
	                     '159-163':{'color':'orange','classification':'Anerobic'},
	                     '164-168':{'color':'lightgreen','classification':'Anerobic'},
	                    '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
           

                    '30':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-115':{'color':'yellow','classification':'Aerobic'},
	                     '116-123':{'color':'lightgreen','classification':'Aerobic'},
	                     '124-145':{'color':'thickgreen','classification':'Aerobic'},
	                    '146-154':{'color':'lightgreen','classification':'Aerobic'},
	                     '155-158':{'color':'yellow','classification':'Aerobic'},
	                     '159-163':{'color':'orange','classification':'Anerobic'},
	                     '164-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
           

                    '31':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-133':{'color':'lightgreen','classification':'Aerobic'},
	                     '134-145':{'color':'thickgreen','classification':'Aerobic'},
	                     '146-154':{'color':'lightgreen','classification':'Aerobic'},
	                     '155-159':{'color':'yellow','classification':'Aerobic'},
	                     '160-167':{'color':'orange','classification':'Anerobic'},
	                     '168-170':{'color':'lightgreen','classification':'Anerobic'},
	                     '171-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 
           
                    
                    '32':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-132':{'color':'lightgreen','classification':'Aerobic'},
	                    '133-145':{'color':'thickgreen','classification':'Aerobic'},
	                     '146-153':{'color':'lightgreen','classification':'Aerobic'},
	                     '154-158':{'color':'yellow','classification':'Aerobic'},
	                     '159-166':{'color':'orange','classification':'Anerobic'},
	                     '167-169':{'color':'lightgreen','classification':'Anerobic'},
	                     '170-178':{'color':'thickgreen','classification':'Anerobic'},
	                    '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                 

                    

                      
                    '33':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-131':{'color':'lightgreen','classification':'Aerobic'},
	                     '132-145':{'color':'thickgreen','classification':'Aerobic'},
	                     '146-152':{'color':'lightgreen','classification':'Aerobic'},
	                     '153-157':{'color':'yellow','classification':'Aerobic'},
	                     '158-165':{'color':'orange','classification':'Anerobic'},
	                     '166-168':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},              


                    '34':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-130':{'color':'lightgreen','classification':'Aerobic'},
	                     '131-145':{'color':'thickgreen','classification':'Aerobic'},
	                     '146-151':{'color':'lightgreen','classification':'Aerobic'},
	                     '152-156':{'color':'yellow','classification':'Aerobic'},
	                     '157-164':{'color':'orange','classification':'Anerobic'},
	                     '165-167':{'color':'lightgreen','classification':'Anerobic'},
	                     '168-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                   

                    '35':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-129':{'color':'lightgreen','classification':'Aerobic'},
	                     '130-145':{'color':'thickgreen','classification':'Aerobic'},
	                     '146-150':{'color':'lightgreen','classification':'Aerobic'},
	                     '151-155':{'color':'yellow','classification':'Aerobic'},
	                     '156-163':{'color':'orange','classification':'Anerobic'},
	                     '164-166':{'color':'lightgreen','classification':'Anerobic'},
	                     '167-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},        


                    '36':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-128':{'color':'lightgreen','classification':'Aerobic'},
	                     '129-144':{'color':'thickgreen','classification':'Aerobic'},
	                     '145-149':{'color':'lightgreen','classification':'Aerobic'},
	                     '150-154':{'color':'yellow','classification':'Aerobic'},
	                     '155-162':{'color':'orange','classification':'Anerobic'},
	                     '163-165':{'color':'lightgreen','classification':'Anerobic'},
	                     '166-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                        '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},           




                    '37':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-113':{'color':'yellow','classification':'Aerobic'},
	                     '114-127':{'color':'lightgreen','classification':'Aerobic'},
	                     '128-143':{'color':'thickgreen','classification':'Aerobic'},
	                     '144-148':{'color':'lightgreen','classification':'Aerobic'},
	                     '149-153':{'color':'yellow','classification':'Aerobic'},
	                     '154-161':{'color':'orange','classification':'Anerobic'},
	                     '162-164':{'color':'lightgreen','classification':'Anerobic'},
	                     '165-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                                          



                    
                    '38':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-112':{'color':'yellow','classification':'Aerobic'},
	                     '113-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-142':{'color':'thickgreen','classification':'Aerobic'},
	                     '143-147':{'color':'lightgreen','classification':'Aerobic'},
	                     '148-152':{'color':'yellow','classification':'Aerobic'},
	                     '153-160':{'color':'orange','classification':'Anerobic'},
	                     '161-163':{'color':'lightgreen','classification':'Anerobic'},
	                     '164-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                                          




                   '39':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-111':{'color':'yellow','classification':'Aerobic'},
	                     '112-125':{'color':'lightgreen','classification':'Aerobic'},
	                     '126-141':{'color':'thickgreen','classification':'Aerobic'},
	                     '142-146':{'color':'lightgreen','classification':'Aerobic'},
	                     '147-151':{'color':'yellow','classification':'Aerobic'},
	                     '152-159':{'color':'orange','classification':'Anerobic'},
	                     '160-162':{'color':'lightgreen','classification':'Anerobic'},
	                     '163-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                         
	
                    
                    '40':{'0-109':{'color':'red','classification':'Below_Aerobic'},
	                     '110-110':{'color':'yellow','classification':'Aerobic'},
	                     '111-124':{'color':'lightgreen','classification':'Aerobic'},
	                     '125-140':{'color':'thickgreen','classification':'Aerobic'},
	                     '141-145':{'color':'lightgreen','classification':'Aerobic'},
	                     '146-150':{'color':'yellow','classification':'Aerobic'},
	                    '151-158':{'color':'orange','classification':'Anerobic'},
	                     '159-161':{'color':'lightgreen','classification':'Anerobic'},
	                     '162-178':{'color':'thickgreen','classification':'Anerobic'},
	                    '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                        '189-240':{'color':'red','classification':'Anerobic'}},                         
	

	                '41':{'0-108':{'color':'red','classification':'Below_Aerobic'},
	                     '109-109':{'color':'yellow','classification':'Aerobic'},
	                     '110-123':{'color':'lightgreen','classification':'Aerobic'},
	                     '124-139':{'color':'thickgreen','classification':'Aerobic'},
	                     '140-144':{'color':'lightgreen','classification':'Aerobic'},
	                     '145-149':{'color':'yellow','classification':'Aerobic'},
	                     '150-157':{'color':'orange','classification':'Anerobic'},
	                     '158-160':{'color':'lightgreen','classification':'Anerobic'},
	                     '161-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                         

                     
                    '42':{'0-107':{'color':'red','classification':'Below_Aerobic'},
	                     '108-108':{'color':'yellow','classification':'Aerobic'},
	                     '109-122':{'color':'lightgreen','classification':'Aerobic'},
	                     '123-138':{'color':'thickgreen','classification':'Aerobic'},
	                     '139-143':{'color':'lightgreen','classification':'Aerobic'},
	                     '144-148':{'color':'yellow','classification':'Aerobic'},
	                     '149-156':{'color':'orange','classification':'Anerobic'},
	                     '157-159':{'color':'lightgreen','classification':'Anerobic'},
	                     '160-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                         



                             
                    '43':{'0-106':{'color':'red','classification':'Below_Aerobic'},
	                     '107-107':{'color':'yellow','classification':'Aerobic'},
	                     '108-121':{'color':'lightgreen','classification':'Aerobic'},
	                     '122-137':{'color':'thickgreen','classification':'Aerobic'},
	                     '138-142':{'color':'lightgreen','classification':'Aerobic'},
	                     '143-147':{'color':'yellow','classification':'Aerobic'},
	                     '148-155':{'color':'orange','classification':'Anerobic'},
	                     '156-158':{'color':'lightgreen','classification':'Anerobic'},
	                     '169-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                         

                    '44':{'0-105':{'color':'red','classification':'Below_Aerobic'},
	                     '106-106':{'color':'yellow','classification':'Aerobic'},
	                     '107-120':{'color':'lightgreen','classification':'Aerobic'},
	                     '121-136':{'color':'thickgreen','classification':'Aerobic'},
	                     '137-141':{'color':'lightgreen','classification':'Aerobic'},
	                     '142-146':{'color':'yellow','classification':'Aerobic'},
	                     '147-154':{'color':'orange','classification':'Anerobic'},
	                     '155-157':{'color':'lightgreen','classification':'Anerobic'},
	                     '158-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  

                    
                    '45':{'0-104':{'color':'red','classification':'Below_Aerobic'},
	                     '105-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-119':{'color':'lightgreen','classification':'Aerobic'},
	                     '120-135':{'color':'thickgreen','classification':'Aerobic'},
	                     '136-140':{'color':'lightgreen','classification':'Aerobic'},
	                     '141-145':{'color':'yellow','classification':'Aerobic'},
	                     '146-153':{'color':'orange','classification':'Anerobic'},
	                     '154-156':{'color':'lightgreen','classification':'Anerobic'},
	                     '157-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  



                       
                    '46':{'0-103':{'color':'red','classification':'Below_Aerobic'},
	                     '104-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-118':{'color':'lightgreen','classification':'Aerobic'},
	                     '119-134':{'color':'thickgreen','classification':'Aerobic'},
	                     '135-139':{'color':'lightgreen','classification':'Aerobic'},
	                     '140-144':{'color':'yellow','classification':'Aerobic'},
	                     '145-152':{'color':'orange','classification':'Anerobic'},
	                     '153-155':{'color':'lightgreen','classification':'Anerobic'},
	                     '156-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  


                           
                    '47':{'0-102':{'color':'red','classification':'Below_Aerobic'},
	                     '103-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-117':{'color':'lightgreen','classification':'Aerobic'},
	                     '118-133':{'color':'thickgreen','classification':'Aerobic'},
	                     '134-138':{'color':'lightgreen','classification':'Aerobic'},
	                     '139-143':{'color':'yellow','classification':'Aerobic'},
	                     '144-151':{'color':'orange','classification':'Anerobic'},
	                     '152-154':{'color':'lightgreen','classification':'Anerobic'},
	                     '155-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  

                      


                    '48':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-116':{'color':'lightgreen','classification':'Aerobic'},
	                     '117-132':{'color':'thickgreen','classification':'Aerobic'},
	                     '133-137':{'color':'lightgreen','classification':'Aerobic'},
	                    '138-142':{'color':'yellow','classification':'Aerobic'},
	                    '143-150':{'color':'orange','classification':'Anerobic'},
	                     '151-153':{'color':'lightgreen','classification':'Anerobic'},
	                     '154-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

                    
                    '49':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-115':{'color':'lightgreen','classification':'Aerobic'},
	                     '116-131':{'color':'thickgreen','classification':'Aerobic'},
	                     '132-136':{'color':'lightgreen','classification':'Aerobic'},
	                     '137-141':{'color':'yellow','classification':'Aerobic'},
	                     '142-149':{'color':'orange','classification':'Anerobic'},
	                     '150-152':{'color':'lightgreen','classification':'Anerobic'},
	                     '153-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  


                     
                    '50':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-114':{'color':'lightgreen','classification':'Aerobic'},
	                     '115-130':{'color':'thickgreen','classification':'Aerobic'},
	                     '131-135':{'color':'lightgreen','classification':'Aerobic'},
	                     '136-140':{'color':'yellow','classification':'Aerobic'},
	                     '141-148':{'color':'orange','classification':'Anerobic'},
	                     '149-151':{'color':'lightgreen','classification':'Anerobic'},
	                     '152-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

                    
                    '51':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-113':{'color':'lightgreen','classification':'Aerobic'},
	                     '114-129':{'color':'thickgreen','classification':'Aerobic'},
	                     '130-134':{'color':'lightgreen','classification':'Aerobic'},
	                     '135-139':{'color':'yellow','classification':'Aerobic'},
	                     '140-147':{'color':'orange','classification':'Anerobic'},
	                     '148-150':{'color':'lightgreen','classification':'Anerobic'},
	                     '151-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                        '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

                    
                    '52':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-112':{'color':'lightgreen','classification':'Aerobic'},
	                     '113-128':{'color':'thickgreen','classification':'Aerobic'},
	                     '129-133':{'color':'lightgreen','classification':'Aerobic'},
	                    '134-138':{'color':'yellow','classification':'Aerobic'},
	                    '139-146':{'color':'orange','classification':'Anerobic'},
	                     '147-149':{'color':'lightgreen','classification':'Anerobic'},
	                     '150-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

                    
                    '53':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-111':{'color':'lightgreen','classification':'Aerobic'},
	                     '112-127':{'color':'thickgreen','classification':'Aerobic'},
	                     '128-132':{'color':'lightgreen','classification':'Aerobic'},
	                     '133-137':{'color':'yellow','classification':'Aerobic'},
	                     '138-145':{'color':'orange','classification':'Anerobic'},
	                     '146-148':{'color':'lightgreen','classification':'Anerobic'},
	                     '149-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

                     
                    '54':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-110':{'color':'lightgreen','classification':'Aerobic'},
	                     '111-126':{'color':'thickgreen','classification':'Aerobic'},
	                     '127-131':{'color':'lightgreen','classification':'Aerobic'},
	                     '132-136':{'color':'yellow','classification':'Aerobic'},
	                    '137-144':{'color':'orange','classification':'Anerobic'},
	                    '145-147':{'color':'lightgreen','classification':'Anerobic'},
	                     '148-178':{'color':'thickgreen','classification':'Anerobic'},
	                     '179-183':{'color':'lightgreen','classification':'Anerobic'},
                         '184-186':{'color':'yellow','classification':'Anerobic'},
                         '187-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  
  
                    
                    '55':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-130':{'color':'lightgreen','classification':'Aerobic'},
	                     '131-135':{'color':'yellow','classification':'Aerobic'},
	                     '136-143':{'color':'orange','classification':'Anerobic'},
	                     '144-148':{'color':'lightgreen','classification':'Anerobic'},
	                     '159-173':{'color':'thickgreen','classification':'Anerobic'},
	                     '174-178':{'color':'lightgreen','classification':'Anerobic'},
                         '179-183':{'color':'yellow','classification':'Anerobic'},
                         '184-188':{'color':'orange','classification':'Anerobic'},
                         '189-240':{'color':'red','classification':'Anerobic'}},                  
  

	
	                
                    '56':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-129':{'color':'lightgreen','classification':'Aerobic'},
	                     '130-134':{'color':'yellow','classification':'Aerobic'},
	                     '135-142':{'color':'orange','classification':'Anerobic'},
	                     '143-147':{'color':'lightgreen','classification':'Anerobic'},
	                     '148-172':{'color':'thickgreen','classification':'Anerobic'},
	                     '173-177':{'color':'lightgreen','classification':'Anerobic'},
                         '178-182':{'color':'yellow','classification':'Anerobic'},
                         '183-187':{'color':'orange','classification':'Anerobic'},
                         '188-240':{'color':'red','classification':'Anerobic'}},                  
  

	
                    
                    '57':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-119':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-128':{'color':'lightgreen','classification':'Aerobic'},
	                     '129-133':{'color':'yellow','classification':'Aerobic'},
	                     '134-141':{'color':'orange','classification':'Anerobic'},
	                     '142-146':{'color':'lightgreen','classification':'Anerobic'},
	                     '147-171':{'color':'thickgreen','classification':'Anerobic'},
	                     '172-176':{'color':'lightgreen','classification':'Anerobic'},
                         '177-181':{'color':'yellow','classification':'Anerobic'},
                         '182-186':{'color':'orange','classification':'Anerobic'},
                         '187-240':{'color':'red','classification':'Anerobic'}},                           
  
                    




                    '58':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-127':{'color':'lightgreen','classification':'Aerobic'},
	                     '128-132':{'color':'yellow','classification':'Aerobic'},
	                     '133-140':{'color':'orange','classification':'Anerobic'},
	                     '141-145':{'color':'lightgreen','classification':'Anerobic'},
	                     '146-170':{'color':'thickgreen','classification':'Anerobic'},
	                     '171-175':{'color':'lightgreen','classification':'Anerobic'},
                         '176-180':{'color':'yellow','classification':'Anerobic'},
                         '181-185':{'color':'orange','classification':'Anerobic'},
                         '186-240':{'color':'red','classification':'Anerobic'}},                  
	


                        
                    '59':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-131':{'color':'yellow','classification':'Aerobic'},
	                     '132-139':{'color':'orange','classification':'Anerobic'},
	                     '140-144':{'color':'lightgreen','classification':'Anerobic'},
	                     '145-169':{'color':'thickgreen','classification':'Anerobic'},
	                     '170-174':{'color':'lightgreen','classification':'Anerobic'},
                         '175-179':{'color':'yellow','classification':'Anerobic'},
                         '180-184':{'color':'orange','classification':'Anerobic'},
                         '185-240':{'color':'red','classification':'Anerobic'}},                  

	
                        
                    '60':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-130':{'color':'yellow','classification':'Aerobic'},
	                     '131-138':{'color':'orange','classification':'Anerobic'},
	                     '139-143':{'color':'lightgreen','classification':'Anerobic'},
	                     '144-168':{'color':'thickgreen','classification':'Anerobic'},
	                     '169-173':{'color':'lightgreen','classification':'Anerobic'},
                         '174-178':{'color':'yellow','classification':'Anerobic'},
                         '179-183':{'color':'orange','classification':'Anerobic'},
                         '184-240':{'color':'red','classification':'Anerobic'}},                  


	                    
                    '61':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-129':{'color':'yellow','classification':'Aerobic'},
	                     '130-137':{'color':'orange','classification':'Anerobic'},
	                     '138-142':{'color':'lightgreen','classification':'Anerobic'},
	                    '143-167':{'color':'thickgreen','classification':'Anerobic'},
	                     '168-172':{'color':'lightgreen','classification':'Anerobic'},
                         '173-177':{'color':'yellow','classification':'Anerobic'},
                         '178-182':{'color':'orange','classification':'Anerobic'},
                         '183-240':{'color':'red','classification':'Anerobic'}},                  

	




                        
                    '62':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-128':{'color':'yellow','classification':'Aerobic'},
	                     '129-136':{'color':'orange','classification':'Anerobic'},
	                     '137-141':{'color':'lightgreen','classification':'Anerobic'},
	                     '142-166':{'color':'thickgreen','classification':'Anerobic'},
	                     '167-171':{'color':'lightgreen','classification':'Anerobic'},
                         '172-176':{'color':'yellow','classification':'Anerobic'},
                        '177-181':{'color':'orange','classification':'Anerobic'},
                         '182-240':{'color':'red','classification':'Anerobic'}},                  


                    


                    '63':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                    '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                    '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-135':{'color':'orange','classification':'Anerobic'},
	                     '136-140':{'color':'lightgreen','classification':'Anerobic'},
	                     '141-165':{'color':'thickgreen','classification':'Anerobic'},
	                    '166-170':{'color':'lightgreen','classification':'Anerobic'},
                         '171-175':{'color':'yellow','classification':'Anerobic'},
                         '176-180':{'color':'orange','classification':'Anerobic'},
                         '181-240':{'color':'red','classification':'Anerobic'}},                  

	

                        
                    '64':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-119':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-128':{'color':'lightgreen','classification':'Aerobic'},
	                     '129-133':{'color':'yellow','classification':'Aerobic'},
	                     '134-141':{'color':'orange','classification':'Anerobic'},
	                     '142-146':{'color':'lightgreen','classification':'Anerobic'},
	                    '147-171':{'color':'thickgreen','classification':'Anerobic'},
	                     '172-176':{'color':'lightgreen','classification':'Anerobic'},
                         '177-181':{'color':'yellow','classification':'Anerobic'},
                         '182-186':{'color':'orange','classification':'Anerobic'},
                         '187-240':{'color':'red','classification':'Anerobic'}},                  
	

                        
                    '65':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                    '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                    '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-133':{'color':'orange','classification':'Anerobic'},
	                     '134-138':{'color':'lightgreen','classification':'Anerobic'},
	                     '139-163':{'color':'thickgreen','classification':'Anerobic'},
	                     '164-168':{'color':'lightgreen','classification':'Anerobic'},
                         '169-173':{'color':'yellow','classification':'Anerobic'},
                         '174-178':{'color':'orange','classification':'Anerobic'},
                         '179-240':{'color':'red','classification':'Anerobic'}},                  

	
                        
                    '66':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-132':{'color':'orange','classification':'Anerobic'},
	                     '133-137':{'color':'lightgreen','classification':'Anerobic'},
	                     '138-162':{'color':'thickgreen','classification':'Anerobic'},
	                     '163-167':{'color':'lightgreen','classification':'Anerobic'},
                         '168-172':{'color':'yellow','classification':'Anerobic'},
                         '173-177':{'color':'orange','classification':'Anerobic'},
                         '178-240':{'color':'red','classification':'Anerobic'}},              



                    '67':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-131':{'color':'orange','classification':'Anerobic'},
	                     '132-136':{'color':'lightgreen','classification':'Anerobic'},
	                     '137-161':{'color':'thickgreen','classification':'Anerobic'},
	                     '162-166':{'color':'lightgreen','classification':'Anerobic'},
                         '167-171':{'color':'yellow','classification':'Anerobic'},
                         '172-176':{'color':'orange','classification':'Anerobic'},
                         '177-240':{'color':'red','classification':'Anerobic'}},                  



                    
                    '68':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-130':{'color':'orange','classification':'Anerobic'},
	                     '131-135':{'color':'lightgreen','classification':'Anerobic'},
	                     '136-160':{'color':'thickgreen','classification':'Anerobic'},
	                     '161-165':{'color':'lightgreen','classification':'Anerobic'},
                         '166-170':{'color':'yellow','classification':'Anerobic'},
                         '171-175':{'color':'orange','classification':'Anerobic'},
                         '176-240':{'color':'red','classification':'Anerobic'}},                  



                      
                    '69':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-129':{'color':'orange','classification':'Anerobic'},
	                     '130-134':{'color':'lightgreen','classification':'Anerobic'},
	                     '135-159':{'color':'thickgreen','classification':'Anerobic'},
	                     '160-164':{'color':'lightgreen','classification':'Anerobic'},
                         '165-169':{'color':'yellow','classification':'Anerobic'},
                        '170-174':{'color':'orange','classification':'Anerobic'},
                         '175-240':{'color':'red','classification':'Anerobic'}},                  


	
                    

                      
                    '70':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-133':{'color':'lightgreen','classification':'Anerobic'},
	                     '134-158':{'color':'thickgreen','classification':'Anerobic'},
	                     '159-163':{'color':'lightgreen','classification':'Anerobic'},
                         '164-168':{'color':'yellow','classification':'Anerobic'},
                         '169-173':{'color':'orange','classification':'Anerobic'},
                         '174-240':{'color':'red','classification':'Anerobic'}},               
	

                        
                    '71':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                    '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-132':{'color':'lightgreen','classification':'Anerobic'},
	                     '133-157':{'color':'thickgreen','classification':'Anerobic'},
	                     '158-162':{'color':'lightgreen','classification':'Anerobic'},
                         '163-167':{'color':'yellow','classification':'Anerobic'},
                         '168-172':{'color':'orange','classification':'Anerobic'},
                         '173-240':{'color':'red','classification':'Anerobic'}},               
	                 




	                 '72':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-131':{'color':'lightgreen','classification':'Anerobic'},
	                     '132-156':{'color':'thickgreen','classification':'Anerobic'},
	                     '157-161':{'color':'lightgreen','classification':'Anerobic'},
                         '162-166':{'color':'yellow','classification':'Anerobic'},
                         '167-171':{'color':'orange','classification':'Anerobic'},
                         '172-240':{'color':'red','classification':'Anerobic'}},               

 
                    '73':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-130':{'color':'lightgreen','classification':'Anerobic'},
	                     '131-155':{'color':'thickgreen','classification':'Anerobic'},
	                     '156-160':{'color':'lightgreen','classification':'Anerobic'},
                         '161-165':{'color':'yellow','classification':'Anerobic'},
                         '166-170':{'color':'orange','classification':'Anerobic'},
                         '171-240':{'color':'red','classification':'Anerobic'}},               
	   


	               

                    '74':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-154':{'color':'thickgreen','classification':'Anerobic'},
	                     '155-159':{'color':'lightgreen','classification':'Anerobic'},
                         '160-164':{'color':'yellow','classification':'Anerobic'},
                         '165-169':{'color':'orange','classification':'Anerobic'},
                         '170-240':{'color':'red','classification':'Anerobic'}},               
	   


                    
                    '75':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-153':{'color':'thickgreen','classification':'Anerobic'},
	                     '154-158':{'color':'lightgreen','classification':'Anerobic'},
                         '159-163':{'color':'yellow','classification':'Anerobic'},
                         '164-168':{'color':'orange','classification':'Anerobic'},
                         '169-240':{'color':'red','classification':'Anerobic'}},           



                    '76':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-152':{'color':'thickgreen','classification':'Anerobic'},
	                     '153-157':{'color':'lightgreen','classification':'Anerobic'},
                         '158-162':{'color':'yellow','classification':'Anerobic'},
                         '163-167':{'color':'orange','classification':'Anerobic'},
                         '168-240':{'color':'red','classification':'Anerobic'}},           
   

                   '77':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-151':{'color':'thickgreen','classification':'Anerobic'},
	                     '152-156':{'color':'lightgreen','classification':'Anerobic'},
                         '157-161':{'color':'yellow','classification':'Anerobic'},
                         '162-166':{'color':'orange','classification':'Anerobic'},
                         '167-240':{'color':'red','classification':'Anerobic'}},           

	
                    
                   '78':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-150':{'color':'thickgreen','classification':'Anerobic'},
	                     '151-155':{'color':'lightgreen','classification':'Anerobic'},
                         '156-160':{'color':'yellow','classification':'Anerobic'},
                         '161-165':{'color':'orange','classification':'Anerobic'},
                         '166-240':{'color':'red','classification':'Anerobic'}},           


                    '79':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '102-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-125':{'color':'thickgreen','classification':'Aerobic'},
	                     '126-126':{'color':'lightgreen','classification':'Aerobic'},
	                     '127-127':{'color':'yellow','classification':'Aerobic'},
	                     '128-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-149':{'color':'thickgreen','classification':'Anerobic'},
	                     '150-154':{'color':'lightgreen','classification':'Anerobic'},
                         '155-159':{'color':'yellow','classification':'Anerobic'},
                         '160-164':{'color':'orange','classification':'Anerobic'},
                         '165-240':{'color':'red','classification':'Anerobic'}},           





                    '80':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-108':{'color':'lightgreen','classification':'Aerobic'},
	                     '109-124':{'color':'thickgreen','classification':'Aerobic'},
	                     '125-125':{'color':'lightgreen','classification':'Aerobic'},
	                     '126-126':{'color':'yellow','classification':'Aerobic'},
	                     '127-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-148':{'color':'thickgreen','classification':'Anerobic'},
	                     '149-153':{'color':'lightgreen','classification':'Anerobic'},
                         '154-158':{'color':'yellow','classification':'Anerobic'},
                         '159-163':{'color':'orange','classification':'Anerobic'},
                         '164-240':{'color':'red','classification':'Anerobic'}},  


                    '81':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-108':{'color':'lightgreen','classification':'Aerobic'},
	                     '109-123':{'color':'thickgreen','classification':'Aerobic'},
	                     '124-124':{'color':'lightgreen','classification':'Aerobic'},
	                     '125-125':{'color':'yellow','classification':'Aerobic'},
	                     '126-128':{'color':'orange','classification':'Anerobic'},
	                    '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                    '130-147':{'color':'thickgreen','classification':'Anerobic'},
	                     '148-152':{'color':'lightgreen','classification':'Anerobic'},
                         '153-157':{'color':'yellow','classification':'Anerobic'},
                         '158-162':{'color':'orange','classification':'Anerobic'},
                         '163-240':{'color':'red','classification':'Anerobic'}},  


                    '82':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-108':{'color':'lightgreen','classification':'Aerobic'},
	                     '109-122':{'color':'thickgreen','classification':'Aerobic'},
	                     '123-123':{'color':'lightgreen','classification':'Aerobic'},
	                     '124-124':{'color':'yellow','classification':'Aerobic'},
	                     '125-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-146':{'color':'thickgreen','classification':'Anerobic'},
	                     '147-151':{'color':'lightgreen','classification':'Anerobic'},
                         '152-156':{'color':'yellow','classification':'Anerobic'},
                         '157-161':{'color':'orange','classification':'Anerobic'},
                         '162-240':{'color':'red','classification':'Anerobic'}},  


	                '83':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-107':{'color':'lightgreen','classification':'Aerobic'},
	                     '108-121':{'color':'thickgreen','classification':'Aerobic'},
	                     '122-122':{'color':'lightgreen','classification':'Aerobic'},
	                     '123-123':{'color':'yellow','classification':'Aerobic'},
	                     '124-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-145':{'color':'thickgreen','classification':'Anerobic'},
	                     '146-150':{'color':'lightgreen','classification':'Anerobic'},
                         '151-155':{'color':'yellow','classification':'Anerobic'},
                         '156-160':{'color':'orange','classification':'Anerobic'},
                         '161-240':{'color':'red','classification':'Anerobic'}},  



	                '84':{'0-101':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-107':{'color':'lightgreen','classification':'Aerobic'},
	                     '108-120':{'color':'thickgreen','classification':'Aerobic'},
	                     '121-121':{'color':'lightgreen','classification':'Aerobic'},
	                     '122-122':{'color':'yellow','classification':'Aerobic'},
	                     '123-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-144':{'color':'thickgreen','classification':'Anerobic'},
	                     '145-149':{'color':'lightgreen','classification':'Anerobic'},
                         '150-154':{'color':'yellow','classification':'Anerobic'},
                         '155-159':{'color':'orange','classification':'Anerobic'},
                         '160-240':{'color':'red','classification':'Anerobic'}},  


                    '85':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-107':{'color':'lightgreen','classification':'Aerobic'},
	                     '108-119':{'color':'thickgreen','classification':'Aerobic'},
	                     '120-120':{'color':'lightgreen','classification':'Aerobic'},
	                     '121-121':{'color':'yellow','classification':'Aerobic'},
	                     '122-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-143':{'color':'thickgreen','classification':'Anerobic'},
	                     '144-148':{'color':'lightgreen','classification':'Anerobic'},
                         '149-153':{'color':'yellow','classification':'Anerobic'},
                         '154-158':{'color':'orange','classification':'Anerobic'},
                         '159-240':{'color':'red','classification':'Anerobic'}},  

 

                    '86':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-106':{'color':'lightgreen','classification':'Aerobic'},
	                     '107-118':{'color':'thickgreen','classification':'Aerobic'},
	                     '119-119':{'color':'lightgreen','classification':'Aerobic'},
	                     '120-120':{'color':'yellow','classification':'Aerobic'},
	                     '121-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-142':{'color':'thickgreen','classification':'Anerobic'},
	                     '143-147':{'color':'lightgreen','classification':'Anerobic'},
                         '148-152':{'color':'yellow','classification':'Anerobic'},
                         '153-157':{'color':'orange','classification':'Anerobic'},
                         '158-240':{'color':'red','classification':'Anerobic'}},  



                                        

                    '87':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-106':{'color':'lightgreen','classification':'Aerobic'},
	                     '107-117':{'color':'thickgreen','classification':'Aerobic'},
	                     '118-118':{'color':'lightgreen','classification':'Aerobic'},
	                     '119-119':{'color':'yellow','classification':'Aerobic'},
	                     '120-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-141':{'color':'thickgreen','classification':'Anerobic'},
	                     '142-146':{'color':'lightgreen','classification':'Anerobic'},
                         '147-151':{'color':'yellow','classification':'Anerobic'},
                         '152-156':{'color':'orange','classification':'Anerobic'},
                         '157-240':{'color':'red','classification':'Anerobic'}},  



                    
                    '88':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-106':{'color':'lightgreen','classification':'Aerobic'},
	                     '107-116':{'color':'thickgreen','classification':'Aerobic'},
	                     '117-117':{'color':'lightgreen','classification':'Aerobic'},
	                     '118-118':{'color':'yellow','classification':'Aerobic'},
	                     '119-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-140':{'color':'thickgreen','classification':'Anerobic'},
	                    '141-145':{'color':'lightgreen','classification':'Anerobic'},
                        '146-150':{'color':'yellow','classification':'Anerobic'},
                         '151-155':{'color':'orange','classification':'Anerobic'},
                         '156-240':{'color':'red','classification':'Anerobic'}},  


                    

                    '89':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-105':{'color':'lightgreen','classification':'Aerobic'},
	                     '106-115':{'color':'thickgreen','classification':'Aerobic'},
	                     '116-116':{'color':'lightgreen','classification':'Aerobic'},
	                     '117-117':{'color':'yellow','classification':'Aerobic'},
	                     '118-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-139':{'color':'thickgreen','classification':'Anerobic'},
	                     '140-144':{'color':'lightgreen','classification':'Anerobic'},
                        '145-149':{'color':'yellow','classification':'Anerobic'},
                         '150-154':{'color':'orange','classification':'Anerobic'},
                         '155-240':{'color':'red','classification':'Anerobic'}},  
	



                    '90':{'0-100':{'color':'red','classification':'Below_Aerobic'},
	                     '101-104':{'color':'yellow','classification':'Aerobic'},
	                     '105-105':{'color':'lightgreen','classification':'Aerobic'},
	                     '106-114':{'color':'thickgreen','classification':'Aerobic'},
	                     '115-115':{'color':'lightgreen','classification':'Aerobic'},
	                     '116-116':{'color':'yellow','classification':'Aerobic'},
	                     '117-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-138':{'color':'thickgreen','classification':'Anerobic'},
	                     '139-143':{'color':'lightgreen','classification':'Anerobic'},
                         '144-148':{'color':'yellow','classification':'Anerobic'},
                         '149-153':{'color':'orange','classification':'Anerobic'},
                         '154-240':{'color':'red','classification':'Anerobic'}},  




                    
                    '91':{'0-99':{'color':'red','classification':'Below_Aerobic'},
	                     '100-103':{'color':'yellow','classification':'Aerobic'},
	                     '104-105':{'color':'lightgreen','classification':'Aerobic'},
	                     '106-113':{'color':'thickgreen','classification':'Aerobic'},
	                     '114-114':{'color':'lightgreen','classification':'Aerobic'},
	                     '115-115':{'color':'yellow','classification':'Aerobic'},
	                     '116-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-137':{'color':'thickgreen','classification':'Anerobic'},
	                     '138-142':{'color':'lightgreen','classification':'Anerobic'},
                         '143-147':{'color':'yellow','classification':'Anerobic'},
                         '148-152':{'color':'orange','classification':'Anerobic'},
                         '153-240':{'color':'red','classification':'Anerobic'}},  




                              
                    '92':{'0-98':{'color':'red','classification':'Below_Aerobic'},
	                     '99-102':{'color':'yellow','classification':'Aerobic'},
	                     '103-104':{'color':'lightgreen','classification':'Aerobic'},
	                     '105-112':{'color':'thickgreen','classification':'Aerobic'},
	                     '113-113':{'color':'lightgreen','classification':'Aerobic'},
	                     '114-114':{'color':'yellow','classification':'Aerobic'},
	                     '115-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-136':{'color':'thickgreen','classification':'Anerobic'},
	                     '137-141':{'color':'lightgreen','classification':'Anerobic'},
                         '142-146':{'color':'yellow','classification':'Anerobic'},
                         '147-151':{'color':'orange','classification':'Anerobic'},
                         '152-240':{'color':'red','classification':'Anerobic'}},  
                    
	
                    '93':{'0-97':{'color':'red','classification':'Below_Aerobic'},
	                     '98-101':{'color':'yellow','classification':'Aerobic'},
	                     '102-104':{'color':'lightgreen','classification':'Aerobic'},
	                     '105-111':{'color':'thickgreen','classification':'Aerobic'},
	                     '112-112':{'color':'lightgreen','classification':'Aerobic'},
	                     '113-113':{'color':'yellow','classification':'Aerobic'},
	                     '114-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-135':{'color':'thickgreen','classification':'Anerobic'},
	                     '136-140':{'color':'lightgreen','classification':'Anerobic'},
                         '141-145':{'color':'yellow','classification':'Anerobic'},
                         '146-150':{'color':'orange','classification':'Anerobic'},
                         '151-240':{'color':'red','classification':'Anerobic'}},  
                    


                    
                    '94':{'0-96':{'color':'red','classification':'Below_Aerobic'},
	                     '97-100':{'color':'yellow','classification':'Aerobic'},
	                     '101-103':{'color':'lightgreen','classification':'Aerobic'},
	                     '104-110':{'color':'thickgreen','classification':'Aerobic'},
	                     '111-111':{'color':'lightgreen','classification':'Aerobic'},
	                     '112-112':{'color':'yellow','classification':'Aerobic'},
	                     '113-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-134':{'color':'thickgreen','classification':'Anerobic'},
	                     '135-139':{'color':'lightgreen','classification':'Anerobic'},
                         '140-144':{'color':'yellow','classification':'Anerobic'},
                         '145-149':{'color':'orange','classification':'Anerobic'},
                         '150-240':{'color':'red','classification':'Anerobic'}},  



                   '95':{'0-95':{'color':'red','classification':'Below_Aerobic'},
	                     '96-99':{'color':'yellow','classification':'Aerobic'},
	                     '100-102':{'color':'lightgreen','classification':'Aerobic'},
	                     '103-109':{'color':'thickgreen','classification':'Aerobic'},
	                     '110-110':{'color':'lightgreen','classification':'Aerobic'},
	                     '111-111':{'color':'yellow','classification':'Aerobic'},
	                     '112-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-133':{'color':'thickgreen','classification':'Anerobic'},
	                     '134-138':{'color':'lightgreen','classification':'Anerobic'},
                         '139-143':{'color':'yellow','classification':'Anerobic'},
                         '144-148':{'color':'orange','classification':'Anerobic'},
                         '149-240':{'color':'red','classification':'Anerobic'}},  

	

                    '96':{'0-94':{'color':'red','classification':'Below_Aerobic'},
	                    '95-98':{'color':'yellow','classification':'Aerobic'},
	                    '99-101':{'color':'lightgreen','classification':'Aerobic'},
	                     '102-108':{'color':'thickgreen','classification':'Aerobic'},
	                     '109-109':{'color':'lightgreen','classification':'Aerobic'},
	                     '110-110':{'color':'yellow','classification':'Aerobic'},
	                    '111-128':{'color':'orange','classification':'Anerobic'},
	                    '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-132':{'color':'thickgreen','classification':'Anerobic'},
	                     '133-137':{'color':'lightgreen','classification':'Anerobic'},
                        '138-142':{'color':'yellow','classification':'Anerobic'},
                         '143-147':{'color':'orange','classification':'Anerobic'},
                        '148-240':{'color':'red','classification':'Anerobic'}},  

	
                    '97':{'0-93':{'color':'red','classification':'Below_Aerobic'},
	                     '94-97':{'color':'yellow','classification':'Aerobic'},
	                     '98-100':{'color':'lightgreen','classification':'Aerobic'},
	                     '101-107':{'color':'thickgreen','classification':'Aerobic'},
	                     '108-108':{'color':'lightgreen','classification':'Aerobic'},
	                     '109-109':{'color':'yellow','classification':'Aerobic'},
	                     '110-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-131':{'color':'thickgreen','classification':'Anerobic'},
	                     '132-136':{'color':'lightgreen','classification':'Anerobic'},
                         '137-141':{'color':'yellow','classification':'Anerobic'},
                         '142-146':{'color':'orange','classification':'Anerobic'},
                         '147-240':{'color':'red','classification':'Anerobic'}},  
	

                    
                    '98':{'0-92':{'color':'red','classification':'Below_Aerobic'},
	                     '93-96':{'color':'yellow','classification':'Aerobic'},
	                     '97-99':{'color':'lightgreen','classification':'Aerobic'},
	                     '100-106':{'color':'thickgreen','classification':'Aerobic'},
	                     '107-107':{'color':'lightgreen','classification':'Aerobic'},
	                     '108-108':{'color':'yellow','classification':'Aerobic'},
	                     '109-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                    '130-130':{'color':'thickgreen','classification':'Anerobic'},
	                    '131-135':{'color':'lightgreen','classification':'Anerobic'},
                         '136-140':{'color':'yellow','classification':'Anerobic'},
                         '141-145':{'color':'orange','classification':'Anerobic'},
                         '146-240':{'color':'red','classification':'Anerobic'}},  
	


                      
                    '99':{'0-91':{'color':'red','classification':'Below_Aerobic'},
	                     '92-95':{'color':'yellow','classification':'Aerobic'},
	                     '96-98':{'color':'lightgreen','classification':'Aerobic'},
	                     '99-105':{'color':'thickgreen','classification':'Aerobic'},
	                     '106-106':{'color':'lightgreen','classification':'Aerobic'},
	                     '107-107':{'color':'yellow','classification':'Aerobic'},
	                     '108-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-130':{'color':'thickgreen','classification':'Anerobic'},
	                     '131-134':{'color':'lightgreen','classification':'Anerobic'},
                         '135-139':{'color':'yellow','classification':'Anerobic'},
                         '140-144':{'color':'orange','classification':'Anerobic'},
                         '145-240':{'color':'red','classification':'Anerobic'}},  



                    '100':{'0-90':{'color':'red','classification':'Below_Aerobic'},
	                     '91-94':{'color':'yellow','classification':'Aerobic'},
	                     '95-97':{'color':'lightgreen','classification':'Aerobic'},
	                     '98-104':{'color':'thickgreen','classification':'Aerobic'},
	                     '105-105':{'color':'lightgreen','classification':'Aerobic'},
	                     '106-106':{'color':'yellow','classification':'Aerobic'},
	                     '107-128':{'color':'orange','classification':'Anerobic'},
	                     '129-129':{'color':'lightgreen','classification':'Anerobic'},
	                     '130-130':{'color':'thickgreen','classification':'Anerobic'},
	                    '131-133':{'color':'lightgreen','classification':'Anerobic'},
                       '134-138':{'color':'yellow','classification':'Anerobic'},
                         '139-143':{'color':'orange','classification':'Anerobic'},
                         '144-240':{'color':'red','classification':'Anerobic'}},  



                    '100-240':{'0-989':{'color':'red','classification':'Below_Aerobic'},
	                     '90-93':{'color':'yellow','classification':'Aerobic'},
	                     '94-96':{'color':'lightgreen','classification':'Aerobic'},
	                     '97-103':{'color':'thickgreen','classification':'Aerobic'},
	                     '104-104':{'color':'lightgreen','classification':'Aerobic'},
	                     '105-105':{'color':'yellow','classification':'Aerobic'},
	                     '106-127':{'color':'orange','classification':'Anerobic'},
	                     '128-128':{'color':'lightgreen','classification':'Anerobic'},
	                     '129-129':{'color':'thickgreen','classification':'Anerobic'},
	                     '130-132':{'color':'lightgreen','classification':'Anerobic'},
                         '133-137':{'color':'yellow','classification':'Anerobic'},
                         '138-142':{'color':'orange','classification':'Anerobic'},
                         '143-240':{'color':'red','classification':'Anerobic'}},


	}
	return aa_dashboard

