# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitconnecttoken',
            name='user_id_fitbit',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
