# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0002_fitbitconnecttoken_user_id_fitbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitconnecttoken',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
