# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0006_userfitbitdataactivities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfitbitdataactivities',
            old_name='date_of_heartrate',
            new_name='date_of_activities',
        ),
    ]
