# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0007_auto_20180329_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitbitdatasleep',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
