# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0009_auto_20180331_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitbitdataactivities',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
