# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 07:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit', '0011_auto_20180404_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitbitDataSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_of_steps', models.TextField()),
                ('steps_data', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit_steps_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
