# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit', '0012_userfitbitdatasteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_date', models.DateField()),
                ('collection_type', models.CharField(choices=[('activities', 'Activities'), ('body', 'Body'), ('foods', 'Foods'), ('sleeps', 'Sleeps')], max_length=100)),
                ('state', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=100)),
                ('notification', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fitbitconnecttoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
