# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0012_userfitbitdatasteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('data_notification', models.TextField()),
            ],
        ),
    ]
