# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0013_fitbitnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitnotifications',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
