# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0014_auto_20180625_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitconnecttoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
