# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 11:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit', '0014_auto_20180716_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitbitDatabody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_of_body', models.TextField()),
                ('body_data', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit_body_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFitbitDatafoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_of_foods', models.TextField()),
                ('foods_data', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit_food_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
