# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0015_fitbitconnecttoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitconnecttoken',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
