# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit', '0016_userfitbitlastsynced'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_client_id', models.CharField(max_length=250)),
                ('user_client_secret', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_app_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
