# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0016_auto_20180710_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitconnecttoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
