# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary_Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Non_Exercise_Steps', models.FloatField(default=datetime.date(2017, 7, 4))),
                ('Non_Exercise_Steps_Grade', models.TextField()),
                ('Movement_When_Not_Sleeping', models.FloatField(help_text='Number of Hours per day Moved less than 300 steps an hour')),
                ('Standing_Work_Station', models.FloatField(help_text='Number of Daysyou stood for 3 hours or more yesterday when you worked(on work days)')),
                ('Movment_Consistency_Grade', models.TextField(help_text='Number of Hours per day Moved less than 300 steps an hour')),
                ('Total_Sleep_In_Hours', models.FloatField()),
                ('Sleep_Aids_To_Aid_Sleep', models.IntegerField(help_text='Number of time you took any prescription or non prescription sleep aids to aid aleep excluding melatonin')),
                ('Overall_Sleep_Grade', models.TextField()),
                ('Bedtime', models.FloatField()),
                ('Awake_From_Sleep', models.IntegerField()),
                ('Resting_Heart_Rate', models.FloatField(help_text='Sleeping')),
                ('Excersice_Consistency', models.IntegerField(help_text='Days Worked Out')),
                ('Average_days_Per_Week_Exercised_Over_Period', models.IntegerField()),
                ('Excersice_Consistency_Grade', models.TextField()),
                ('Overall_Exercise_Score', models.FloatField()),
                ('Overall_Exercise_Grade', models.TextField()),
                ('Workout_Duration', models.FloatField()),
                ('Workout_Duration_Grade', models.TextField()),
                ('Workout_Effort_Level', models.FloatField()),
                ('Workout_Effort_Level_Grade', models.TextField()),
                ('Average_Exercise_Heartrate', models.IntegerField()),
                ('Average_Exercise_Heartrate_Grade', models.TextField()),
                ('Non_Processed_Food_Consumed', models.FloatField(help_text='percentage')),
                ('Non_Processed_Food_Consumed_Grade', models.TextField(help_text='percentage')),
                ('Average_Drinks_Per_Day', models.FloatField(help_text='Alcohol')),
                ('Average_Drinks_Per_Week', models.FloatField(help_text='Alcohol')),
                ('Average_Drinks_Grade', models.TextField(help_text='Based on weekly consumption of Alcohol')),
            ],
        ),
    ]
