# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-21 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataBackfillRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('apple', 'Apple')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processed', 'Processed'), ('processing', 'Processing'), ('failed', 'Failed')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
