# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabackfillrequest',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processed', 'Processed'), ('processing', 'Processing'), ('failed', 'Failed')], default='Unprocessed', max_length=100),
        ),
    ]
