# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190212_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('new', models.TextField()),
                ('enjoy', models.TextField()),
                ('feel', models.TextField()),
                ('rate', models.IntegerField()),
                ('expect', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
