# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='expect',
            field=models.BooleanField(default=False),
        ),
    ]
