# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-05 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190403_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
