# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190405_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
