# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('did_you_measure_HRR', models.CharField(blank=True, max_length=3)),
                ('did_heartrate_reach_99', models.CharField(blank=True, max_length=3)),
                ('time_99', models.IntegerField(blank=True, null=True)),
                ('hrr_start_beat', models.IntegerField(blank=True, null=True)),
                ('lowest_hrr_1min', models.IntegerField(blank=True, null=True)),
                ('No_beats_recovered', models.IntegerField(blank=True, null=True)),
                ('end_time_activity', models.IntegerField(blank=True, null=True)),
                ('diff_actity_hrr', models.IntegerField(blank=True, null=True)),
                ('HRR_activity_start_time', models.IntegerField(blank=True, null=True)),
                ('end_heartrate_activity', models.IntegerField(blank=True, null=True)),
                ('heart_rate_down_up', models.IntegerField(blank=True, null=True)),
                ('pure_1min_heart_beats', models.IntegerField(blank=True, null=True)),
                ('pure_time_99', models.IntegerField(blank=True, null=True)),
                ('no_fitfile_hrr_reach_99', models.CharField(blank=True, max_length=3)),
                ('no_fitfile_hrr_time_reach_99', models.IntegerField(blank=True, null=True)),
                ('lowest_hrr_no_fitfile', models.IntegerField(blank=True, null=True)),
                ('no_file_beats_recovered', models.IntegerField(blank=True, null=True)),
                ('offset', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='hrr',
            index=models.Index(fields=['user', '-created_at'], name='hrr_hrr_user_id_10ca40_idx'),
        ),
        migrations.AddIndex(
            model_name='hrr',
            index=models.Index(fields=['created_at'], name='hrr_hrr_created_5a8c5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hrr',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
