# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0003_auto_20180514_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrr',
            name='Did_heartrate_reach_99',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='Did_you_measure_HRR',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='no_fitfile_hrr_reach_99',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
