# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0005_auto_20180515_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrr',
            name='HRR_activity_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='HRR_start_beat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='No_beats_recovered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='diff_actity_hrr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='end_heartrate_activity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='end_time_activity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='heart_rate_down_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='lowest_hrr_1min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='lowest_hrr_no_fitfile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='no_file_beats_recovered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='no_fitfile_hrr_time_reach_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='pure_1min_heart_beats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='pure_time_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrr',
            name='time_99',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
