# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0006_auto_20180515_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrr',
            name='time_heart_rate_reached_99',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
