# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0007_hrr_time_heart_rate_reached_99'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('total_duration', models.FloatField(blank=True, null=True)),
                ('duration_in_aerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_aerobic', models.FloatField(blank=True, null=True)),
                ('duration_in_anaerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_anaerobic', models.FloatField(blank=True, null=True)),
                ('duration_below_aerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_below_aerobic', models.FloatField(blank=True, null=True)),
                ('duration_hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('percent_hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('user_aa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeHeartZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heart_rate_zone_low_end', models.CharField(blank=True, max_length=3, null=True)),
                ('heart_rate_zone_high_end', models.CharField(blank=True, max_length=3, null=True)),
                ('time_in_zone_for_last_7_days', models.CharField(blank=True, max_length=10, null=True)),
                ('prcnt_total_duration_in_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
