# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-16 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0008_auto_20180612_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('total_duration', models.FloatField(blank=True, null=True)),
                ('duration_in_aerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_aerobic', models.FloatField(blank=True, null=True)),
                ('duration_in_anaerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_anaerobic', models.FloatField(blank=True, null=True)),
                ('duration_below_aerobic_range', models.FloatField(blank=True, null=True)),
                ('percent_below_aerobic', models.FloatField(blank=True, null=True)),
                ('duration_hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('percent_hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('user_aa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeHeartZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heart_rate_zone_low_end', models.TextField(blank=True, null=True)),
                ('heart_rate_zone_high_end', models.TextField(blank=True, null=True)),
                ('time_in_zone_for_last_7_days', models.TextField(blank=True, null=True)),
                ('prcnt_total_duration_in_zone', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='timeheartzones',
            index=models.Index(fields=['user', '-created_at'], name='hrr_timehea_user_id_3aa12a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeheartzones',
            index=models.Index(fields=['created_at'], name='hrr_timehea_created_c7baae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeheartzones',
            unique_together=set([('user', 'created_at')]),
        ),
        migrations.AddIndex(
            model_name='aacalculations',
            index=models.Index(fields=['user_aa', '-created_at'], name='hrr_aacalcu_user_aa_a231ba_idx'),
        ),
        migrations.AddIndex(
            model_name='aacalculations',
            index=models.Index(fields=['created_at'], name='hrr_aacalcu_created_b425f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aacalculations',
            unique_together=set([('user_aa', 'created_at')]),
        ),
    ]
