# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0008_aacalculations_timeheartzones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AaCalculations',
            new_name='AaCalculation',
        ),
        migrations.RenameModel(
            old_name='TimeHeartZones',
            new_name='TimeHeartZone',
        ),
    ]
