# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0012_auto_20180623_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaWorkoutCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('user_aa_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='aaworkoutcalculations',
            index=models.Index(fields=['user_aa_workout', '-created_at'], name='hrr_aaworko_user_aa_f67a43_idx'),
        ),
        migrations.AddIndex(
            model_name='aaworkoutcalculations',
            index=models.Index(fields=['created_at'], name='hrr_aaworko_created_dbcb38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aaworkoutcalculations',
            unique_together=set([('user_aa_workout', 'created_at')]),
        ),
    ]
