# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0014_auto_20180707_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aa',
            name='aerobic_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aa',
            name='anaerobic_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aa',
            name='below_aerobic_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
