# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0015_auto_20180707_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrr',
            name='Did_heartrate_reach_99',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
