# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0016_auto_20180904_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrr',
            name='no_fitfile_hrr_reach_99',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
