# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-26 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0017_auto_20180904_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('aerobic_zone', models.FloatField(blank=True, null=True)),
                ('anaerobic_zone', models.FloatField(blank=True, null=True)),
                ('below_aerobic_zone', models.FloatField(blank=True, null=True)),
                ('aerobic_range', models.CharField(blank=True, max_length=20, null=True)),
                ('anaerobic_range', models.CharField(blank=True, max_length=20, null=True)),
                ('below_aerobic_range', models.CharField(blank=True, max_length=20, null=True)),
                ('hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('percent_hrr_not_recorded', models.FloatField(blank=True, null=True)),
                ('percent_aerobic', models.FloatField(blank=True, null=True)),
                ('percent_below_aerobic', models.FloatField(blank=True, null=True)),
                ('percent_anaerobic', models.FloatField(blank=True, null=True)),
                ('total_percent', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='aaheartrate',
            index=models.Index(fields=['user', '-created_at'], name='hrr_aaheart_user_id_4f9bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='aaheartrate',
            index=models.Index(fields=['created_at'], name='hrr_aaheart_created_0d9f51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aaheartrate',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
