# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0018_auto_20181226_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AAHeartRate',
            new_name='AAWholeDay',
        ),
        migrations.RemoveIndex(
            model_name='aawholeday',
            name='hrr_aaheart_user_id_4f9bc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='aawholeday',
            name='hrr_aaheart_created_0d9f51_idx',
        ),
        migrations.AddIndex(
            model_name='aawholeday',
            index=models.Index(fields=['user', '-created_at'], name='hrr_aawhole_user_id_e96d48_idx'),
        ),
        migrations.AddIndex(
            model_name='aawholeday',
            index=models.Index(fields=['created_at'], name='hrr_aawhole_created_2f4257_idx'),
        ),
    ]
