# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrr', '0020_auto_20190102_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AAWholeDay',
            new_name='TwentyfourHourAA',
        ),
        migrations.RemoveIndex(
            model_name='twentyfourhouraa',
            name='hrr_aawhole_user_id_e96d48_idx',
        ),
        migrations.RemoveIndex(
            model_name='twentyfourhouraa',
            name='hrr_aawhole_created_2f4257_idx',
        ),
        migrations.AddIndex(
            model_name='twentyfourhouraa',
            index=models.Index(fields=['user', '-created_at'], name='hrr_twentyf_user_id_0b2363_idx'),
        ),
        migrations.AddIndex(
            model_name='twentyfourhouraa',
            index=models.Index(fields=['created_at'], name='hrr_twentyf_created_d4f994_idx'),
        ),
    ]
