# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-27 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0021_auto_20190102_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AACustomRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerobic_range', models.CharField(blank=True, max_length=255, null=True)),
                ('anaerobic_range', models.CharField(blank=True, max_length=255, null=True)),
                ('below_aerobic_range', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
