# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-14 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrr', '0023_aacustomranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAdashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='aadashboard',
            index=models.Index(fields=['user', '-created_at'], name='hrr_aadashb_user_id_2ca992_idx'),
        ),
        migrations.AddIndex(
            model_name='aadashboard',
            index=models.Index(fields=['created_at'], name='hrr_aadashb_created_513aef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aadashboard',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
