# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 04:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_User_Input_Encouraged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level_yesterday', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=4)),
                ('pains_twings_during_or_after_your_workout', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('water_consumed_during_workout', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('workout_that_user_breathed_through_nose', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Daily_User_Input_Optional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_of_processed_food_consumed_yesterday', models.CharField(max_length=264)),
                ('Chia_seeds_consumed_during_workout', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('fasted_during_workout', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=264)),
                ('General_Workout_Comments', models.CharField(max_length=256)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(500)])),
                ('waist_size', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)])),
                ('clothes_size', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('Heart_Rate_Variability', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Daily_User_Input_Strong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_out_Easy_or_hard', models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard')], max_length=4)),
                ('work_out_effort_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('unprocessed_food_consumed_yesterday', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Number_of_alcohol_consumed_yesterday', models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10')], max_length=2)),
                ('sleep_aids_last_night', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('prescription_or_non_prescription_sleep_aids_last_night', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('smoke_any_substances_whatsoever', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('medications_or_controlled_substances_yesterday', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(choices=[('Maintain overall health', 'Maintain overall health'), ('improve health', 'improve health'), ('improve energy levels', 'improve energy levels'), ('improve blood work levels', 'improve blood work levels'), ('weight loss/waist size reduction', 'weight loss/waist size reduction'), ('reduce stress/anxiety', 'reduce stress/anxiety'), ('train for a running race', 'train for a running race'), ('train for a triathlon', 'train for a triathlon'), ('get faster as an athlete', 'get faster as an athlete'), ('qualify for the Boston marathon', 'qualify for the Boston marathon'), ('qualify for a world level triathlon_ironman kona_half ironman world championships', 'qualify for a world level triathlon(ironman kona/half ironman world championships)'), ('completely transform my life', 'completely transform my life'), ('be proud to look in the mirror again', 'be proud to look in the mirror again'), ('other', 'other')], max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Inputs_Changes_from_Third_Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resting_Heart_Rate', models.FloatField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(125)])),
                ('Sleep_time_excluding_awake_time', models.CharField(max_length=264)),
                ('Other', models.CharField(max_length=264)),
                ('TBD', models.CharField(max_length=264)),
            ],
        ),
    ]
