# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_user_input_optional',
            old_name='Chia_seeds_consumed_during_workout',
            new_name='chia_seeds_consumed_during_workout',
        ),
        migrations.RenameField(
            model_name='daily_user_input_optional',
            old_name='General_Workout_Comments',
            new_name='general_Workout_Comments',
        ),
        migrations.RenameField(
            model_name='daily_user_input_optional',
            old_name='Heart_Rate_Variability',
            new_name='heart_Rate_Variability',
        ),
        migrations.RenameField(
            model_name='daily_user_input_optional',
            old_name='List_of_processed_food_consumed_yesterday',
            new_name='list_of_processed_food_consumed_yesterday',
        ),
        migrations.RenameField(
            model_name='daily_user_input_strong',
            old_name='Number_of_alcohol_consumed_yesterday',
            new_name='number_of_alcohol_consumed_yesterday',
        ),
        migrations.RenameField(
            model_name='inputs_changes_from_third_sources',
            old_name='Other',
            new_name='other',
        ),
        migrations.RenameField(
            model_name='inputs_changes_from_third_sources',
            old_name='Resting_Heart_Rate',
            new_name='resting_Heart_Rate',
        ),
        migrations.RenameField(
            model_name='inputs_changes_from_third_sources',
            old_name='Sleep_time_excluding_awake_time',
            new_name='sleep_time_excluding_awake_time',
        ),
        migrations.RenameField(
            model_name='inputs_changes_from_third_sources',
            old_name='TBD',
            new_name='tbd',
        ),
    ]
