# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='daily_user_input_strong',
            name='prescription_or_non_prescription_sleep_aids_last_night',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daily_user_input_strong',
            name='smoke_any_substances_whatsoever',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daily_user_input_encouraged',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_input.User'),
        ),
        migrations.AddField(
            model_name='daily_user_input_optional',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_input.User'),
        ),
        migrations.AddField(
            model_name='daily_user_input_strong',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_input.User'),
        ),
        migrations.AddField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_input.User'),
        ),
        migrations.AddField(
            model_name='inputs_changes_from_third_sources',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_input.User'),
        ),
    ]
