# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0002_auto_20170828_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_User_Input_Encouraged',
            new_name='DailyUserInputEncouraged',
        ),
        migrations.RenameModel(
            old_name='Daily_User_Input_Optional',
            new_name='DailyUserInputOptional',
        ),
        migrations.RenameModel(
            old_name='Daily_User_Input_Strong',
            new_name='DailyUserInputStrong',
        ),
        migrations.RenameModel(
            old_name='Inputs_Changes_from_Third_Sources',
            new_name='InputsChangesFromThirdSources',
        ),
    ]
