# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0003_auto_20170828_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
