# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0004_auto_20170902_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyinput',
            name='created_at',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
