# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0005_auto_20170902_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserinputoptional',
            old_name='heart_Rate_Variability',
            new_name='heart_rate_variability',
        ),
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='work_out_Easy_or_hard',
            new_name='work_out_easy_or_hard',
        ),
        migrations.RenameField(
            model_name='inputschangesfromthirdsources',
            old_name='resting_Heart_Rate',
            new_name='resting_heart_rate',
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encouraged_input', to='user_input.UserDailyInput'),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optional_input', to='user_input.UserDailyInput'),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strong_input', to='user_input.UserDailyInput'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='user_input.UserDailyInput'),
        ),
        migrations.AlterField(
            model_name='inputschangesfromthirdsources',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_source_input', to='user_input.UserDailyInput'),
        ),
    ]
