# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 13:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_input', '0010_auto_20170927_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='unprocessed_food_consumed_yesterday',
            new_name='prcnt_unprocessed_food_consumed_yesterday',
        ),
        migrations.RemoveField(
            model_name='dailyuserinputoptional',
            name='sick_comment',
        ),
        migrations.RemoveField(
            model_name='dailyuserinputstrong',
            name='sleep_aids_last_night',
        ),
        migrations.RemoveField(
            model_name='dailyuserinputstrong',
            name='work_out_effort_level',
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='calories_consumed_during_workout',
            field=models.IntegerField(default=76),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='food_ate_before_workout',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='foot_ate_during_workout',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='sickness',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='type_of_diet_eaten',
            field=models.CharField(default='vegan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='workout_enjoyable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='hard_portion_workout_effort_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='list_of_unprocessed_food_consumed_yesterday',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='medications_or_controlled_substances_taken',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='sleep_aid_taken',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='sleep_time_excluding_awake_time',
            field=models.CharField(default='2017-10-2', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='smoked_substance',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='workout_effort_level',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='pain_area',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='pains_twings_during_or_after_your_workout',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='stress_level_yesterday',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='water_consumed_during_workout',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='clothes_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='fasted_during_workout',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='list_of_processed_food_consumed_yesterday',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='sick',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='stand_for_three_hours',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='medications_or_controlled_substances_yesterday',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prescription_or_non_prescription_sleep_aids_last_night',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='smoke_any_substances_whatsoever',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='work_out_easy_or_hard',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('no workout today', 'No Workout Today')], max_length=4),
        ),
        migrations.AlterField(
            model_name='userdailyinput',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='userdailyinput',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
