# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 06:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0011_auto_20171002_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='pains_twings_during_or_after_your_workout',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('no workout today', 'No workout today')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='clothes_size',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='general_Workout_Comments',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='heart_rate_variability',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='stand_for_three_hours',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='type_of_diet_eaten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='waist_size',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
