# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 14:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0012_auto_20171003_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserinputoptional',
            old_name='foot_ate_during_workout',
            new_name='food_ate_during_workout',
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='workout_that_user_breathed_through_nose',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='clothes_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='percent_breath_nose_all_day_not_exercising',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='percent_breath_nose_last_night',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='waist_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prcnt_unprocessed_food_consumed_yesterday',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
