# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 15:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0013_auto_20171004_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='heart_rate_variability',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='list_of_processed_food_consumed_yesterday',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='workout_enjoyable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('no workout today', 'No Workout Today')], max_length=3),
        ),
    ]
