# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import user_input.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0014_auto_20171004_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='pains_twings_during_or_after_your_workout',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no workout today', 'No workout today')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='stress_level_yesterday',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='water_consumed_during_workout',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='workout_that_user_breathed_through_nose',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='calories_consumed_during_workout',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='chia_seeds_consumed_during_workout',
            field=models.CharField(blank=True, max_length=20, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='clothes_size',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='fasted_during_workout',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no workout today', 'No Workout Today')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='heart_rate_variability',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(1), user_input.models.CharMaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='percent_breath_nose_all_day_not_exercising',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(1), user_input.models.CharMaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='percent_breath_nose_last_night',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(1), user_input.models.CharMaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='sick',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='waist_size',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(20), user_input.models.CharMaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(30), user_input.models.CharMaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='workout_enjoyable',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no workout today', 'No Workout Today')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='hard_portion_workout_effort_level',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='medications_or_controlled_substances_yesterday',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='number_of_alcohol_consumed_yesterday',
            field=models.FloatField(blank=True, choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prcnt_unprocessed_food_consumed_yesterday',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prescription_or_non_prescription_sleep_aids_last_night',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='sleep_time_excluding_awake_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='smoke_any_substances_whatsoever',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='work_out_easy_or_hard',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard'), ('no workout today', 'No Workout Today')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='workout_effort_level',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(10)]),
        ),
    ]
