# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0015_auto_20171009_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='type_of_diet_eaten',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('paleo', 'paleo'), ('low carb/high fat', 'Low carb/high fat'), ('other', 'Other')], max_length=100),
        ),
    ]
