# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0018_auto_20171009_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='number_of_alcohol_consumed_yesterday',
            field=models.CharField(blank=True, choices=[('', '-'), (0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='work_out_easy_or_hard',
            field=models.CharField(blank=True, choices=[('', '-'), ('easy', 'Easy'), ('hard', 'Hard'), ('no workout today', 'No Workout Today')], max_length=20),
        ),
    ]
