# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import user_input.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0019_auto_20171009_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='pain_area',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='food_ate_before_workout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='food_ate_during_workout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(30), user_input.models.CharMaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='medications_or_controlled_substances_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='smoked_substance',
            field=models.TextField(blank=True),
        ),
    ]
