# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0021_auto_20171011_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='type_of_diet_eaten',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
