# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0023_auto_20171012_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='workout',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not yet', 'Not Yet')], default='yes', max_length=3),
            preserve_default=False,
        ),
    ]
