# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0025_dailyuserinputstrong_sleep_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='general_Workout_Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='sleep_aid_taken',
            field=models.TextField(blank=True),
        ),
    ]
