# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0027_auto_20171027_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='general_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='sickness',
            field=models.TextField(blank=True),
        ),
    ]
