# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0028_auto_20171027_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='alcohol_drink_consumed_list',
            field=models.TextField(blank=True),
        ),
    ]
