# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0029_dailyuserinputstrong_alcohol_drink_consumed_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='list_of_processed_food_consumed_yesterday',
            field=models.TextField(blank=True),
        ),
    ]
