# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0033_auto_20171104_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('both', 'Both')], max_length=10),
        ),
    ]
