# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0034_dailyuserinputstrong_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='workout_input_type',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('strength', 'Strength')], max_length=10),
        ),
    ]
