# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import user_input.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0035_dailyuserinputstrong_workout_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[user_input.models.CharMinValueValidator(30), user_input.models.CharMaxValueValidator(300)]),
        ),
    ]
