# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0036_auto_20171117_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='medications_or_controlled_substances_taken',
            new_name='prescription_or_non_prescription_medication_taken',
        ),
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='medications_or_controlled_substances_yesterday',
            new_name='prescription_or_non_prescription_medication_yesterday',
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='controlled_uncontrolled_substance',
            field=models.CharField(blank=True, choices=[('', '-'), ('yes', 'Yes'), ('no', 'NO'), ('decline', 'I Decline')], max_length=4),
        ),
    ]
