# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0037_auto_20171121_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='controlled_uncontrolled_substance',
            field=models.CharField(blank=True, choices=[('', '-'), ('yes', 'Yes'), ('no', 'No'), ('decline', 'I Decline')], max_length=4),
        ),
    ]
