# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0038_auto_20171127_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='awake_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='sleep_awake_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='sleep_bedtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='sleep_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
