# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import user_input.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0042_auto_20171219_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='water_consumed_during_workout',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='dailyuserinputencouraged',
            name='workout_that_user_breathed_through_nose',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user_input.models.CharMinValueValidator(0), user_input.models.CharMaxValueValidator(100)]),
        ),
    ]
