# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0042_auto_20171222_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyinput',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
