# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0043_userdailyinput_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='work_out_easy_or_hard',
            field=models.CharField(blank=True, choices=[('', '-'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('no workout today', 'No Workout Today')], max_length=20),
        ),
    ]
