# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0044_auto_20180119_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='comments_no_workout',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='reason_no_workout',
            field=models.CharField(blank=True, choices=[('rest day', 'Rest Day'), ('sick', 'Sick'), ('too busy/not enough time', 'Too Busy/Not Enough Time'), ('didn’t feel like it', 'Didn’t Feel Like It'), ('work got in the way', 'Work Got in the Way'), ('travel day', 'Travel Day'), ('weather', 'Weather'), ('other', 'Other')], max_length=100),
        ),
    ]
