# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0045_auto_20180130_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='comments_no_workout',
            new_name='no_exercise_comment',
        ),
        migrations.RenameField(
            model_name='dailyuserinputstrong',
            old_name='reason_no_workout',
            new_name='no_exercise_reason',
        ),
    ]
