# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0046_auto_20180130_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='strength_workout_end',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='strength_workout_start',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
