# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0047_auto_20180207_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputoptional',
            name='type_of_diet_eaten',
            field=models.TextField(blank=True),
        ),
    ]
