# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0048_auto_20180212_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='no_exercise_reason',
            field=models.CharField(blank=True, choices=[('rest day', 'Rest Day'), ('injured', 'Injured'), ('sick', 'Sick'), ('too busy/not enough time', 'Too Busy/Not Enough Time'), ('didn’t feel like it', 'Didn’t Feel Like It'), ('work got in the way', 'Work Got in the Way'), ('travel day', 'Travel Day'), ('weather', 'Weather'), ('other', 'Other')], max_length=100),
        ),
    ]
