# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0049_auto_20180305_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='travel',
            field=models.CharField(blank=True, choices=[('', '-'), ('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='travel_destination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputoptional',
            name='travel_purpose',
            field=models.TextField(blank=True),
        ),
    ]
