# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0051_userdailyinput_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='controlled_uncontrolled_substance',
            field=models.CharField(blank=True, choices=[('', '-'), ('yes', 'Yes'), ('no', 'No'), ('decline', 'I Decline')], max_length=10),
        ),
    ]
