# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0052_auto_20180423_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='activities',
            field=models.TextField(blank=True),
        ),
    ]
