# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_input', '0055_auto_20180806_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('activity_data', models.TextField()),
                ('activity_weather', models.TextField(blank=True)),
                ('can_update_steps_type', models.BooleanField(default=True)),
                ('steps_type', models.CharField(choices=[('exercise', 'Exercise'), ('non_exercise', 'Non Exercise')], max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('duplicate', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', 'activity_id'], name='user_input__user_id_f33fd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together=set([('user', 'activity_id')]),
        ),
    ]
