# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0057_dailyactivity_start_time_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prescription_or_non_prescription_medication_yesterday',
            field=models.CharField(blank=True, choices=[('', ''), ('', '-'), ('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='prescription_or_non_prescription_sleep_aids_last_night',
            field=models.CharField(blank=True, choices=[('', ''), ('', '-'), ('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dailyuserinputstrong',
            name='smoke_any_substances_whatsoever',
            field=models.CharField(blank=True, choices=[('', ''), ('', '-'), ('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
    ]
