# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0057_dailyactivity_start_time_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='activity_source',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
