# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0060_auto_20190430_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='list_of_pants_consumed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyuserinputstrong',
            name='no_plants_consumed',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
