# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 15:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_day', models.CharField(blank=True, max_length=4)),
                ('alcohol_week', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_speed', models.FloatField(blank=True, null=True)),
                ('avg_power', models.FloatField(blank=True, null=True)),
                ('avg_speed_per_mile', models.FloatField(blank=True, null=True)),
                ('avg_cadence', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAndReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_easy_hard', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('workout_type', models.CharField(blank=True, choices=[('trademil run', 'Trademil Run'), ('outdoor run', 'Outdoor Run'), ('bike', 'Bike'), ('swim', 'Swim'), ('elliptical', 'Elliptical')], max_length=20)),
                ('workout_time', models.CharField(blank=True, max_length=10)),
                ('workout_location', models.TextField(blank=True)),
                ('workout_duration', models.CharField(blank=True, max_length=10)),
                ('maximum_elevation_workout', models.IntegerField(blank=True, null=True)),
                ('minutes_walked_before_workout', models.CharField(blank=True, max_length=10)),
                ('distance_run', models.FloatField(blank=True, null=True)),
                ('distance_bike', models.FloatField(blank=True, null=True)),
                ('distance_swim', models.FloatField(blank=True, null=True)),
                ('distance_other', models.FloatField(blank=True, null=True)),
                ('pace', models.CharField(blank=True, max_length=10)),
                ('avg_heartrate', models.TextField(blank=True)),
                ('avg_exercise_heartrate', models.FloatField(blank=True, null=True)),
                ('elevation_gain', models.IntegerField(blank=True, null=True)),
                ('elevation_loss', models.IntegerField(blank=True, null=True)),
                ('effort_level', models.PositiveIntegerField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temperature_feels_like', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('hrr', models.CharField(blank=True, max_length=10)),
                ('hrr_start_point', models.IntegerField(blank=True, null=True)),
                ('hrr_beats_lowered', models.IntegerField(blank=True, null=True)),
                ('sleep_resting_hr_last_night', models.IntegerField(blank=True, null=True)),
                ('vo2_max', models.FloatField(blank=True, null=True)),
                ('running_cadence', models.IntegerField(blank=True, null=True)),
                ('nose_breath_prcnt_workout', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('water_consumed_workout', models.FloatField(blank=True, null=True)),
                ('chia_seeds_consumed_workout', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('fast_before_workout', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('pain', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('pain_area', models.TextField(blank=True)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=6)),
                ('sick', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('drug_consumed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('drug', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('smoke_substance', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('exercise_fifteen_more', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('workout_elapsed_time', models.CharField(blank=True, max_length=10)),
                ('timewatch_paused_workout', models.CharField(blank=True, max_length=10)),
                ('exercise_consistency', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('heartrate_variability_stress', models.IntegerField(blank=True, null=True)),
                ('fitness_age', models.IntegerField(blank=True, null=True)),
                ('workout_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prcnt_non_processed_food', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('non_processed_food', models.TextField(blank=True)),
                ('processed_food', models.TextField(blank=True)),
                ('diet_type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_health_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('overall_health_gpa', models.FloatField(blank=True, null=True)),
                ('movement_non_exercise_steps_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('movement_consistency_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('avg_sleep_per_night_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('avg_sleep_per_night_gpa', models.FloatField(blank=True, null=True)),
                ('exercise_consistency_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('exercise_consistency_score', models.FloatField(blank=True, null=True)),
                ('overall_workout_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('overall_workout_gpa', models.FloatField(blank=True, null=True)),
                ('workout_duration_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('workout_duration_gpa', models.FloatField(blank=True, null=True)),
                ('workout_effortlvl_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('workout_effortlvl_gpa', models.FloatField(blank=True, null=True)),
                ('avg_exercise_hr_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('avg_exercise_hr_gpa', models.FloatField(blank=True, null=True)),
                ('prcnt_unprocessed_food_consumed_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('alcoholic_drink_per_week_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3)),
                ('sleep_aid_penalty', models.FloatField(blank=True, null=True)),
                ('ctrl_subs_penalty', models.FloatField(blank=True, null=True)),
                ('smoke_penalty', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_per_wearable', models.CharField(blank=True, max_length=10)),
                ('sleep_per_user_input', models.CharField(blank=True, max_length=10)),
                ('sleep_aid', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sleep_bed_time', models.CharField(blank=True, max_length=20)),
                ('sleep_awake_time', models.CharField(blank=True, max_length=20)),
                ('deep_sleep', models.CharField(blank=True, max_length=10)),
                ('light_sleep', models.CharField(blank=True, max_length=10)),
                ('awake_time', models.CharField(blank=True, max_length=10)),
                ('sleep_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_exercise_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('total_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_climed', models.PositiveIntegerField(blank=True, null=True)),
                ('movement_consistency', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwimStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace_per_100_yard', models.FloatField(blank=True, null=True)),
                ('total_strokes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuickLook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='swimstats',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swim_stats_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='steps',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steps_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='grades',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='food',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='exerciseandreporting',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_reporting_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='bikestats',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bike_stats_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AddField(
            model_name='alcohol',
            name='user_ql',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_ql', to='quicklook.UserQuickLook'),
        ),
        migrations.AlterUniqueTogether(
            name='userquicklook',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
