# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='prcnt_non_processed_food_consumed_grade',
            new_name='prcnt_unprocessed_food_consumed_grade',
        ),
    ]
