# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseandreporting',
            old_name='hrr_start_time',
            new_name='hrr_start_point',
        ),
        migrations.AddField(
            model_name='exerciseandreporting',
            name='temperature_feels_like',
            field=models.FloatField(default=67),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='minutes_walked_before_workout',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_time',
            field=models.TimeField(),
        ),
    ]
