# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0002_grades_movement_non_exercise_steps_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='prcnt_unprocessed_food_consumed_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
