# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0003_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='hrr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='minutes_walked_before_workout',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='pace',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='timewatch_paused_workout',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_elapsed_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='awake_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='deep_sleep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='light_sleep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_awake_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_bed_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_per_user_input',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_per_wearable',
            field=models.CharField(max_length=10),
        ),
    ]
