# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0005_auto_20171106_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='alcohol_day',
            field=models.CharField(max_length=4),
        ),
    ]
