# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0005_auto_20180213_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='alcoholic_drink_per_week_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
