# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0006_auto_20171107_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='vo2_max',
            field=models.FloatField(),
        ),
    ]
