# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0007_exerciseandreporting_did_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseandreporting',
            name='activities_duration',
            field=models.TextField(blank=True),
        ),
    ]
