# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quicklook', '0007_auto_20171107_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquicklook',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='userquicklook',
            unique_together=set([('user', 'created_at')]),
        ),
    ]
