# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0006_auto_20171106_1747'),
        ('quicklook', '0008_auto_20171107_1238'),
    ]

    operations = [
    ]
