# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0008_exerciseandreporting_activities_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='rem_sleep',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
