# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0009_merge_20171107_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='alcohol_day',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='dew_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='humidity',
            field=models.FloatField(),
        ),
    ]
