# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0009_sleep_rem_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
