# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0010_auto_20171108_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquicklook',
            name='created_at',
            field=models.DateField(),
        ),
    ]
