# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-31 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0010_steps_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='restless_sleep',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
