# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0011_auto_20171109_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='drug',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='fast_before_workout',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='pain',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='pain_area',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet_type',
            field=models.TextField(),
        ),
    ]
