# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0011_sleep_restless_sleep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('user_ql', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_ql', to='quicklook.UserQuickLook')),
            ],
        ),
    ]
