# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0012_auto_20171110_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='penalty',
            field=models.IntegerField(),
        ),
    ]
