# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0012_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='user_ql',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='detail',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
