# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0013_auto_20190130_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='user',
            new_name='user_ql',
        ),
    ]
