# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0013_auto_20190508_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='list_of_pants_consumed_ql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='no_plants_consumed_ql',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
