# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0014_auto_20190130_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='end_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
