# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0015_auto_20190130_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='start_time',
            field=models.DateField(),
        ),
    ]
