# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0015_auto_20171127_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseandreporting',
            old_name='distance',
            new_name='distance_bike',
        ),
        migrations.AddField(
            model_name='exerciseandreporting',
            name='distance_other',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseandreporting',
            name='distance_run',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseandreporting',
            name='distance_swim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
