# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0016_auto_20190130_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
