# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0017_auto_20171128_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseandreporting',
            name='fitness_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
