# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 13:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0018_exerciseandreporting_fitness_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='alcohol_day',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='alcohol_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikestats',
            name='avg_cadence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikestats',
            name='avg_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikestats',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikestats',
            name='avg_speed_per_mile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='avg_heartrate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='avg_heartrate_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='chia_seeds_consumed_workout',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='dew_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='distance_bike',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='distance_other',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='distance_run',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='distance_swim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='drug_consumed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='effort_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='elevation_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='exercise_consistency',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='exercise_fifteen_more',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='fitness_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='heartrate_variability_stress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='hrr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='hrr_beats_lowered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='hrr_start_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='maximum_elevation_workout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='medication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='minutes_walked_before_workout',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='nose_breath_prcnt_workout',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='overall_workout_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='pace',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='running_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='sick',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='sleep_resting_hr_last_night',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='smoke_substance',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=6),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='temperature_feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='timewatch_paused_workout',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='vo2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='water_consumed_workout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='wind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_duration_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_easy_hard',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=4),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_effortlvl_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_elapsed_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('trademil run', 'Trademil Run'), ('outdoor run', 'Outdoor Run'), ('bike', 'Bike'), ('swim', 'Swim'), ('elliptical', 'Elliptical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='non_processed_food',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='prcnt_non_processed_food',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='prcnt_non_processed_food_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='alcoholic_drink_per_week_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='avg_sleep_per_night_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='exercise_consistency_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='movement_consistency_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='movement_non_exercise_steps_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='overall_truth_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='overall_truth_health_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='overall_workout_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grades',
            name='penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='prcnt_unprocessed_food_consumed_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='awake_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='deep_sleep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='light_sleep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_aid',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_awake_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_bed_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_per_wearable',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='steps',
            name='exercise_steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='floor_climed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='floor_decended',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='non_exercise_steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='total_steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimstats',
            name='pace_per_100_yard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimstats',
            name='total_strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
