# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0019_auto_20171129_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='avg_exercise_hr_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AddField(
            model_name='grades',
            name='workout_duration_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.AddField(
            model_name='grades',
            name='workout_effortlvl_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
    ]
