# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0020_auto_20171211_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='avg_heartrate_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='overall_workout_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_duration_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_effortlvl_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='prcnt_non_processed_food_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='alcoholic_drink_per_week_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='avg_exercise_hr_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='avg_sleep_per_night_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='exercise_consistency_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='movement_consistency_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='movement_non_exercise_steps_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='overall_truth_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='overall_workout_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='prcnt_unprocessed_food_consumed_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='workout_duration_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='grades',
            name='workout_effortlvl_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], max_length=3),
        ),
    ]
