# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0021_auto_20171212_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='overall_truth_health_gpa',
            new_name='overall_health_gpa',
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='overall_truth_grade',
            new_name='overall_health_grade',
        ),
    ]
