# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0022_auto_20171212_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseandreporting',
            name='avg_heartrate_grade',
        ),
        migrations.RemoveField(
            model_name='exerciseandreporting',
            name='overall_workout_grade',
        ),
        migrations.RemoveField(
            model_name='exerciseandreporting',
            name='workout_duration_grade',
        ),
        migrations.RemoveField(
            model_name='exerciseandreporting',
            name='workout_effortlvl_grade',
        ),
        migrations.RemoveField(
            model_name='food',
            name='prcnt_non_processed_food_grade',
        ),
    ]
