# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0023_auto_20171214_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='floor_decended',
        ),
    ]
