# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0024_remove_steps_floor_decended'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='sleep_aid_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
