# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0025_grades_sleep_aid_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='penalty',
        ),
        migrations.AddField(
            model_name='grades',
            name='ctrl_subs_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='smoke_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
