# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0026_auto_20180108_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='sleep_comments',
            field=models.TextField(blank=True),
        ),
    ]
