# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0027_sleep_sleep_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='avg_exercise_hr_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='avg_sleep_per_night_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='exercise_consistency_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='overall_workout_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='workout_duration_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='workout_effortlvl_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
