# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0028_auto_20180119_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseandreporting',
            name='workout_easy_hard',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
