# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0029_auto_20180126_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='processed_food',
            field=models.TextField(blank=True),
        ),
    ]
