# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0030_food_processed_food'),
        ('quicklook', '0030_auto_20180127_1513'),
    ]

    operations = [
    ]
