# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0030_auto_20180127_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='processed_food',
            field=models.TextField(blank=True),
        ),
    ]
