# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklook', '0030_food_processed_food'),
        ('quicklook', '0031_food_processed_food'),
    ]

    operations = [
    ]
