# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('oh_gpa', 'Overall Health GPA'), ('mne_gpa', 'Movement Non Exercise GPA'), ('mc', 'Movement Consistency'), ('avg_sleep', 'Average Sleep'), ('ec', 'Exercise Consistency'), ('prcnt_uf', 'Percent Unprocessed Food'), ('alcohol_drink', 'Alcohol Drink'), ('total_steps', 'Total Steps'), ('floor_climbed', 'Floor Climbed'), ('resting_hr', 'Resting Heart Rate'), ('deep_sleep', 'Deep Sleep'), ('light_sleep', 'Light Sleep'), ('awake_time', 'Awake Time')], max_length=200)),
                ('score', models.FloatField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['category', '-created_at'], name='leaderboard_categor_4d4600_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['created_at'], name='leaderboard_created_311d46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=set([('user', 'category', 'created_at')]),
        ),
    ]
