# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20180221_0907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderBoard',
            new_name='Scores',
        ),
        migrations.RemoveIndex(
            model_name='scores',
            name='leaderboard_categor_4d4600_idx',
        ),
        migrations.RemoveIndex(
            model_name='scores',
            name='leaderboard_created_311d46_idx',
        ),
        migrations.AddIndex(
            model_name='scores',
            index=models.Index(fields=['category', '-created_at'], name='leaderboard_categor_112d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='scores',
            index=models.Index(fields=['created_at'], name='leaderboard_created_8bf441_idx'),
        ),
    ]
