# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20180223_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
        migrations.AlterModelManagers(
            name='score',
            managers=[
                ('leaderboard', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_categor_112d0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_created_8bf441_idx',
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['category', '-created_at'], name='leaderboard_categor_d00e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['created_at'], name='leaderboard_created_8a81ad_idx'),
        ),
    ]
