# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_auto_20180223_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('oh_gpa', 'Overall Health GPA'), ('mne_gpa', 'Movement Non Exercise GPA'), ('mc', 'Movement Consistency'), ('avg_sleep', 'Average Sleep'), ('ec', 'Exercise Consistency'), ('prcnt_uf', 'Percent Unprocessed Food'), ('alcohol_drink', 'Alcohol Drink'), ('total_steps', 'Total Steps'), ('floor_climbed', 'Floors Climbed'), ('resting_hr', 'Resting Heart Rate'), ('deep_sleep', 'Deep Sleep'), ('awake_time', 'Awake Time')], max_length=200),
        ),
    ]
