# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20180418_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('oh_gpa', 'Overall Health GPA'), ('nes', 'Non Exercise Steps'), ('mc', 'Movement Consistency'), ('avg_sleep', 'Average Sleep'), ('ec', 'Exercise Consistency'), ('prcnt_uf', 'Percent Unprocessed Food'), ('alcohol', 'Alcohol'), ('total_steps', 'Total Steps'), ('floor_climbed', 'Floors Climbed'), ('resting_hr', 'Resting Heart Rate'), ('deep_sleep', 'Deep Sleep'), ('awake_time', 'Awake Time')], max_length=200),
        ),
    ]
