# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caluculated_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(choices=[('Maintain overall health', 'Maintain overall health'), ('improve health', 'improve health'), ('improve energy levels', 'improve energy levels'), ('improve blood work levels', 'improve blood work levels'), ('weight loss/waist size reduction', 'weight loss/waist size reduction'), ('reduce stress/anxiety', 'reduce stress/anxiety'), ('train for a running race', 'train for a running race'), ('train for a triathlon', 'train for a triathlon'), ('get faster as an athlete', 'get faster as an athlete'), ('qualify for the Boston marathon', 'qualify for the Boston marathon'), ('qualify for a world level triathlon_ironman kona_half ironman world championships', 'qualify for a world level triathlon(ironman kona/half ironman world championships)'), ('completely transform my life', 'completely transform my life'), ('be proud to look in the mirror again', 'be proud to look in the mirror again'), ('other', 'other')], max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=264)),
                ('Height', models.FloatField(max_length=264)),
                ('Weight', models.FloatField(max_length=264)),
                ('Date_of_Birth', models.DateField(max_length=8)),
                ('First_name', models.CharField(max_length=264)),
                ('Last_name', models.CharField(max_length=264)),
                ('Garmin_User_Name', models.CharField(max_length=264)),
                ('Garmin_Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
