# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caluculated_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=264)),
                ('height', models.FloatField(blank=True, default=None, max_length=264, null=True)),
                ('weight', models.FloatField(blank=True, default=None, max_length=264, null=True)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('garmin_user_name', models.CharField(max_length=264)),
                ('garmin_password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('goals', models.CharField(choices=[('Maintain overall health', 'Maintain overall health'), ('improve health', 'improve health'), ('improve energy levels', 'improve energy levels'), ('improve blood work levels', 'improve blood work levels'), ('weight loss/waist size reduction', 'weight loss/waist size reduction'), ('reduce stress/anxiety', 'reduce stress/anxiety'), ('train for a running race', 'train for a running race'), ('train for a triathlon', 'train for a triathlon'), ('get faster as an athlete', 'get faster as an athlete'), ('qualify for the Boston marathon', 'qualify for the Boston marathon'), ('qualify for a world level triathlon_ironman kona_half ironman world championships', 'qualify for a world level triathlon(ironman kona/half ironman world championships)'), ('completely transform my life', 'completely transform my life'), ('be proud to look in the mirror again', 'be proud to look in the mirror again'), ('other', 'other')], max_length=264, null=True)),
                ('other', models.CharField(blank=True, max_length=264, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
