# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_input',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='garmin_password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='garmin_user_name',
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
    ]
