# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170805_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_input',
            name='other',
        ),
    ]
