# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_user_input_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_input',
            name='other',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
