# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180117_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsconditions',
            old_name='terms_conditions_text',
            new_name='terms_conditions_version',
        ),
    ]
