# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regitration', '0004_auto_20170623_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_input',
            name='Height',
            field=models.FloatField(default=None, max_length=264),
        ),
    ]
