# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_terms_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleep_goals',
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
