# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20181120_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invited', models.BooleanField(default=True)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('invited_on',),
            },
        ),
    ]
