# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20181117_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goals',
        ),
    ]
