# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_profile_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sleep_goals',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
