# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170807_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_input',
            name='highlighted',
        ),
    ]
