# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
