# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_user_input_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_input',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
