# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_profile_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleep_goals',
        ),
    ]
