# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20181117_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_goals',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
