# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20170807_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_input',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
