# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20181117_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sleep_goals',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
