# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170807_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_input',
            old_name='Aerobic_Heart_Rate_Zone_High_Number',
            new_name='aerobic_heart_rate_zone_high_number',
        ),
        migrations.RenameField(
            model_name='user_input',
            old_name='Aerobic_Heart_Rate_Zone_Low_Number',
            new_name='aerobic_heart_rate_zone_low_number',
        ),
    ]
