# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20170807_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_input',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True, unique=True),
        ),
    ]
