# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20181117_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
