# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0013_auto_20170807_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('height', models.FloatField(max_length=264)),
                ('weight', models.FloatField(max_length=264)),
                ('date_of_birth', models.DateField()),
                ('goals', models.CharField(choices=[('Maintain overall health', 'Maintain overall health'), ('Improve health', 'improve health'), ('Improve energy levels', 'improve energy levels'), ('Improve blood work levels', 'improve blood work levels'), ('Weight loss/waist size reduction', 'weight loss/waist size reduction'), ('Reduce stress/anxiety', 'reduce stress/anxiety'), ('Train for a running race', 'train for a running race'), ('Train for a triathlon', 'train for a triathlon'), ('Get faster as an athlete', 'get faster as an athlete'), ('Qualify for the Boston marathon', 'qualify for the Boston marathon'), ('Qualify for a world level triathlon_ironman kona_half ironman world championships', 'qualify for a world level triathlon(ironman kona/half ironman world championships)'), ('Completely transform my life', 'completely transform my life'), ('Be proud to look in the mirror again', 'be proud to look in the mirror again'), ('other', 'other')], max_length=264, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Caluculated_Fields',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User_Input',
        ),
    ]
