# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20170824_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=6),
        ),
    ]
