# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20170824_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goals',
            field=models.CharField(choices=[('maintain_overall_health', 'Maintain_overall_health')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(max_length=3),
        ),
    ]
