# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20181117_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
