# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20181117_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_goals',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
