# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-19 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20181119_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
