# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGarminDataActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataBodyComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_composition_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataEpoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epoch_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataManuallyUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manually_updated_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataSleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_in_seconds', models.IntegerField(db_index=True)),
                ('start_time_duration_in_seconds', models.IntegerField(db_index=True)),
                ('data', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergarmindata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGarminData',
        ),
    ]
