# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0003_auto_20170905_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergarmindataactivity',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergarmindatabodycomposition',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergarmindatadaily',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergarmindataepoch',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergarmindatamanuallyupdated',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergarmindatasleep',
            name='summary_id',
            field=models.CharField(db_index=True, default='EXAMPLE_SUMMARY1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergarmindataactivity',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindataactivity',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatabodycomposition',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatabodycomposition',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatadaily',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatadaily',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindataepoch',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindataepoch',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatamanuallyupdated',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatamanuallyupdated',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatasleep',
            name='start_time_duration_in_seconds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergarmindatasleep',
            name='start_time_in_seconds',
            field=models.IntegerField(blank=True),
        ),
    ]
