# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0007_auto_20170907_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergarmindataactivity',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarmindatabodycomposition',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarmindatadaily',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarmindataepoch',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarmindatamanuallyupdated',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarmindatasleep',
            name='data',
            field=models.TextField(),
        ),
    ]
