# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garmin', '0009_usergarmindatastressdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGarminDataMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(db_index=True, max_length=100)),
                ('record_date_in_seconds', models.IntegerField()),
                ('calendar_date', models.DateField()),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGarminDataMoveIQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(db_index=True, max_length=100)),
                ('record_date_in_seconds', models.IntegerField()),
                ('start_time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('start_time_duration_in_seconds', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveiq_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
