# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0015_auto_20180315_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garminfitfiles',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
