# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0016_auto_20180316_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminfitfiles',
            name='fit_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
