# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0019_auto_20180326_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminfitfiles',
            name='fit_file',
            field=models.TextField(blank=True),
        ),
    ]
