# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0020_auto_20180326_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminfitfiles',
            name='fit_file_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='garminfitfiles',
            name='fit_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
