# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0021_auto_20180326_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminfitfiles',
            name='fit_file_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
