# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0022_garminfitfiles_fit_file_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garminfitfiles',
            name='fit_file',
        ),
        migrations.RemoveField(
            model_name='garminfitfiles',
            name='fit_file_text',
        ),
    ]
