# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0023_auto_20180327_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garminfitfiles',
            old_name='fit_file_binary',
            new_name='fit_file',
        ),
    ]
