# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garmin', '0024_auto_20180329_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminPingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_start_time_seconds', models.IntegerField(blank=True, null=True)),
                ('summary_type', models.CharField(choices=[('dailies', 'Dailies'), ('activities', 'Activities'), ('manuallyUpdatedActivities', 'Manually Updated Activities'), ('epochs', 'Epochs'), ('sleeps', 'Sleeps'), ('bodyComps', 'Body Composition'), ('stressDetails', 'Stress Details'), ('moveIQActivities', 'Move IQ Activities'), ('userMetrics', 'User Metrics'), ('deregistration', 'Deregistration')], max_length=100)),
                ('notification', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='garminpingnotification',
            index=models.Index(fields=['user', 'upload_start_time_seconds'], name='garmin_garm_user_id_54c4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='garminpingnotification',
            index=models.Index(fields=['-created_at'], name='garmin_garm_created_352598_idx'),
        ),
        migrations.AddIndex(
            model_name='garminpingnotification',
            index=models.Index(fields=['upload_start_time_seconds'], name='garmin_garm_upload__6a0297_idx'),
        ),
    ]
