# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garmin', '0027_auto_20180508_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastSynced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced', models.DateTimeField()),
                ('offset', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_synced', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
