# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0028_userlastsynced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminpingnotification',
            name='summary_type',
            field=models.CharField(choices=[('dailies', 'Dailies'), ('activities', 'Activities'), ('manuallyUpdatedActivities', 'Manually Updated Activities'), ('epochs', 'Epochs'), ('sleeps', 'Sleeps'), ('bodyComps', 'Body Composition'), ('stressDetails', 'Stress Details'), ('moveIQActivities', 'Move IQ Activities'), ('userMetrics', 'User Metrics'), ('deregistrations', 'Deregistration')], max_length=100),
        ),
    ]
