# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0029_auto_20180526_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminfitfiles',
            name='fit_file_belong_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
