# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0030_garminfitfiles_fit_file_belong_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminfitfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
