# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garmin', '0031_auto_20181023_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminfitfiles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
