# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0003_auto_20170707_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_Drinks_Grade',
            field=models.CharField(blank=True, default=None, help_text='Based on weekly consumption of Alcohol', max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_Drinks_Per_Day',
            field=models.IntegerField(blank=True, default=None, help_text='Alcohol'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_Drinks_Per_Week',
            field=models.IntegerField(blank=True, default=None, help_text='Alcohol'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_Exercise_Heartrate',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_Exercise_Heartrate_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Average_days_Per_Week_Exercised_Over_Period',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Awake_From_Sleep',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Bedtime',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Excersice_Consistency',
            field=models.IntegerField(blank=True, default=None, help_text='Days Worked Out'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Excersice_Consistency_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Movment_Consistency_Grade',
            field=models.CharField(blank=True, default=None, help_text='Number of Hours per day Moved less than 300 steps an hour', max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Non_Processed_Food_Consumed',
            field=models.IntegerField(blank=True, default=None, help_text='percentage'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Non_Processed_Food_Consumed_Grade',
            field=models.CharField(blank=True, default=None, help_text='percentage', max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Overall_Exercise_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Overall_Exercise_Score',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Overall_Sleep_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Resting_Heart_Rate',
            field=models.IntegerField(blank=True, default=None, help_text='Sleeping'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Sleep_Aids_To_Aid_Sleep',
            field=models.IntegerField(blank=True, default=None, help_text='Number of time you took any prescription or non prescription sleep aids to aid aleep excluding melatonin'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Standing_Work_Station',
            field=models.IntegerField(blank=True, default=None, help_text='Number of Daysyou stood for 3 hours or more yesterday when you worked(on work days)'),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Total_Sleep_In_Hours',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Workout_Duration',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Workout_Duration_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Workout_Effort_Level',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='summary_desktop',
            name='Workout_Effort_Level_Grade',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
    ]
