# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0002_auto_20180118_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_overall_workout_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
