# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0003_exercisestatscumulative_cum_overall_workout_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativesum',
            name='created_at',
            field=models.DateField(),
        ),
    ]
