# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0004_auto_20180130_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='overall_exercise_rank',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
