# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0005_exercisestatscumulative_overall_exercise_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cum_hrr_time_to_99_in_mins', models.FloatField(blank=True, null=True)),
                ('cum_hrr_beats_lowered_in_first_min', models.IntegerField(blank=True, null=True)),
                ('cum_highest_hr_in_first_min', models.IntegerField(blank=True, null=True)),
                ('cum_hrr_lowest_hr_point', models.IntegerField(blank=True, null=True)),
                ('cum_floors_climbed', models.IntegerField(blank=True, null=True)),
                ('user_cum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_stats_cum', to='progress_analyzer.CumulativeSum')),
            ],
        ),
        migrations.RemoveField(
            model_name='penaltycumulative',
            name='user_cum',
        ),
        migrations.RenameField(
            model_name='nutritioncumulative',
            old_name='cum_prcnt_processed_food_consumed_gpa',
            new_name='cum_prcnt_unprocessed_food_consumed_gpa',
        ),
        migrations.RemoveField(
            model_name='alcoholcumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='exerciseconsistencycumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='exercisestatscumulative',
            name='cum_overall_exercise_gpa',
        ),
        migrations.RemoveField(
            model_name='exercisestatscumulative',
            name='cum_overall_workout_gpa',
        ),
        migrations.RemoveField(
            model_name='exercisestatscumulative',
            name='overall_exercise_rank',
        ),
        migrations.RemoveField(
            model_name='exercisestatscumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='movementconsistencycumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='nonexercisestepscumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='nutritioncumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='overallhealthgradecumulative',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='sleeppernightcumulative',
            name='rank',
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_vo2_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_aid_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisestatscumulative',
            name='cum_avg_exercise_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritioncumulative',
            name='cum_prcnt_unprocessed_food_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PenaltyCumulative',
        ),
    ]
