# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0006_auto_20180213_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherStats',
            new_name='OtherStatsCumulative',
        ),
    ]
