# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0007_auto_20180213_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_resting_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
