# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0009_auto_20180315_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacumulative',
            name='cum_avg_exercise_hr_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
