# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0014_sickcumulative_standingcumulative_stresscumulative_travelcumulative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickcumulative',
            name='cum_reported_sick_days_count',
        ),
        migrations.RemoveField(
            model_name='standingcumulative',
            name='cum_reported_stand_three_hours_days_count',
        ),
        migrations.RemoveField(
            model_name='stresscumulative',
            name='cum_reported_stress_days_count',
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_reported_alcohol_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_reported_sick_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_reported_stand_three_hours_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_reported_stress_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
