# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0016_progressreportupdatemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreportupdatemeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pa_update_meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
