# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0017_auto_20180417_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_hrr_pure_1_min_beats_lowered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_hrr_pure_time_to_99',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
