# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0018_auto_20180709_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacumulative',
            name='cum_hrr_pure_1_minute_beat_lowered_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_hrr_pure_time_to_99_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
