# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0019_auto_20180710_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacumulative',
            name='cum_hrr_activity_end_hr_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_hrr_activity_end_hr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
