# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0020_auto_20180723_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_days_garmin_stress_lvl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
