# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0022_auto_20181009_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_exercise_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
