# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0023_auto_20181025_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacumulative',
            name='cum_sleep_reported_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
