# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0024_metacumulative_cum_sleep_reported_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_hr_aerobic_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_hr_anaerobic_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_hr_below_aerobic_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_hr_not_recorded_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_weekly_workout_duration_in_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
