# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0025_auto_20190301_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_alcohol_drink_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_inputs_reported_days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
