# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0026_auto_20190307_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_avg_non_strength_exercise_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_total_exercise_activities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_total_strength_activities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
