# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_analyzer', '0027_auto_20190318_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_days_alcohol_week_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_days_alcohol_week_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_days_alcohol_week_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_days_alcohol_week_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alcoholcumulative',
            name='cum_days_alcohol_week_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseconsistencycumulative',
            name='cum_days_ec_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseconsistencycumulative',
            name='cum_days_ec_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseconsistencycumulative',
            name='cum_days_ec_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseconsistencycumulative',
            name='cum_days_ec_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseconsistencycumulative',
            name='cum_days_ec_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_days_workout_dur_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_days_workout_dur_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_days_workout_dur_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_days_workout_dur_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatscumulative',
            name='cum_days_workout_dur_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacumulative',
            name='cum_have_garmin_stress_days_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_act_min_no_sleep_exec_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_act_min_no_sleep_exec_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_act_min_no_sleep_exec_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_act_min_no_sleep_exec_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_act_min_no_sleep_exec_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_mcs_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_mcs_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_mcs_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_mcs_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_mcs_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_total_act_min_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_total_act_min_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_total_act_min_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_total_act_min_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementconsistencycumulative',
            name='cum_days_total_act_min_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_above_10k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_above_20k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_above_25k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_above_30k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_above_40k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_nes_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_above_10k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_above_20k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_above_25k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_above_30k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_above_40k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonexercisestepscumulative',
            name='cum_days_ts_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioncumulative',
            name='cum_days_ufood_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioncumulative',
            name='cum_days_ufood_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioncumulative',
            name='cum_days_ufood_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioncumulative',
            name='cum_days_ufood_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioncumulative',
            name='cum_days_ufood_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_days_resting_hr_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_days_resting_hr_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_days_resting_hr_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_days_resting_hr_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstatscumulative',
            name='cum_days_resting_hr_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallhealthgradecumulative',
            name='cum_days_ohg_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallhealthgradecumulative',
            name='cum_days_ohg_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallhealthgradecumulative',
            name='cum_days_ohg_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallhealthgradecumulative',
            name='cum_days_ohg_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallhealthgradecumulative',
            name='cum_days_ohg_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppernightcumulative',
            name='cum_days_sleep_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_garmin_stress_days_got_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_garmin_stress_days_got_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_garmin_stress_days_got_c',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_garmin_stress_days_got_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresscumulative',
            name='cum_garmin_stress_days_got_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
