# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regitration', '0002_remove_registration_input_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caluculated_fields',
            name='Date_of_Birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regitration.Registration_Input'),
        ),
        migrations.AddField(
            model_name='goals',
            name='other',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
